### ISSUE TITLE
wrong carbonlink request from

### ISSUE THREAD

**Issue by AlexAkulov** [go-graphite/go-carbon#11]
1) Я всё время получаю эту ошибку, и графики периодически отстают. 

```
[2015-06-09 20:07:01] W [carbonlink] wrong carbonlink request from: 127.0.0.1:41268
[2015-06-09 20:07:01] W [carbonlink] wrong carbonlink request from: 127.0.0.1:41276
[2015-06-09 20:07:01] W [carbonlink] wrong carbonlink request from: 127.0.0.1:41269
```

2) Как отключить такие сообщения в логе? У меня 9 Гигабайт логов за сутки.

```
[2015-06-09 20:13:16] W bad message: "mongodb.gra.databases.gra.users.wiredTiger.btree.row-store internal pages 0 1433862609\n"
```

3) Я так понимаю что пока reload не поддерживается? Делаю kill -HUP $(pgrep go-carbon), в логе вижу сообщение о принятии, но ничего не меняется.

**Comment by lomik** [comment]
1) Это всякие таймауты от graphite-web. Думаю сделать просто график с количеством плохих запросов и убрать из логов. 
2) А кто шлет такие графики? Они же неправильные - вот он и ругается на них. Тут отправлятор графиков нужно фиксить.
3) Не поддерживается. На HUP только лог-файл переоткрывается. Я думаю что в будущем поддержу, но скорее всего не в ближайшие месяцы.

**Comment by AlexAkulov** [comment]
Роман, спасибо за ответ и сам проект.  
Это отправляет diamond с коллектором mongodb. Понятно что его нужно фиксить, но у сервера я полагаю должен быть какой то log level и такие сообщения должны быть в режиме дебага.

**Comment by lomik** [comment]
В ближайшее время добавлю в конфиг опцию выбора уровня ошибки bad message (или отключения ее совсем).

**Comment by AlexAkulov** [comment]
отлично. спасибо!

**Comment by lomik** [comment]
2) В `master`-е ошибка про "bad message" переехала в уровень Info в `TCP`\- и `Pickle`-ресиверах. В `UDP`-ресивере она и так была Info.
В конфиге появилась опция `log-level` для регулирования уровня логирования.
Войдет в следующий релиз

**Comment by lomik** [comment]
1) Сообщение об ошибке стало более детальным и разделилось на несколько частей:
- Ошибки чтения запроса (таймауты и тд.) переместились в уровень Debug (по-умолчанию выключен)
- Ошибки парсинга pickle остались в уровне warning. Если они будут в логе, то что-то пошло не так

**Comment by lomik** [comment]
Вошло в релиз version 0.5.1
