### ISSUE TITLE
logfile doesn't reopen on delete

### ISSUE THREAD

**Issue by drawks** [go-graphite/go-carbon#112]
I have been doing various experiments with the logfile handling code from this project and today I noticed that, contrary to:

https://github.com/lomik/go-carbon/blob/master/logging/logger.go#L86-L90

It seems that, at least on linux, deleting the open logfile doesn't result in the fd being closed and the logfile being reopened.

**Comment by lomik** [comment]
Logging has been rewritten in 0.10.0
