### ISSUE TITLE
cache max-size and input-buffer units?

### ISSUE THREAD

**Issue by EvanKuhn** [go-graphite/go-carbon#127]
I've been increasing the cache's `max-size` and `input-buffer` settings to reduce cache overflows, which were resulting in lost metrics.  However, I can't figure out what exactly the units are for these settings.  Bytes?  Points?  How large is a point?

If this could be clarified in the readme, that would be great.

Thanks!

**Comment by maggnus** [comment]
+1

**Comment by lomik** [comment]
Same as MAX_CACHE_SIZE in carbon-cache: https://github.com/graphite-project/carbon/blob/master/conf/carbon.conf.example#L57

Limitation in points. Unfortunately, there is no strict memory consumption depending on the number of points. 

It depends on the following factors:
* average metric name length
* the number of unique metrics in the cache
