### ISSUE TITLE
[Packaging] RPM update to support systemd-based OS

### ISSUE THREAD

**Issue by mgrzybek** [go-graphite/go-carbon#128]
Hi,

I have updated some files to create a RPM package that deals with systemd:
* conf-examples/carbon.conf: path updates for logs, data and schema
* deploy/rpm: added logrotate + service file

In order to create a clean PR, I have some questions:

1. Do you want a spec file per distribution release?
   * go-carbon.spec.centos, go-carbon.spec.suse...

2. Do you want a generic logrotate file?
   * buildrpm.sh could create it on the fly depending on carbon.conf and the target OS

Mathieu

**Comment by lomik** [comment]
Hi,

I already have refactoring plan. All paths will be changed in release 0.10 (not next 0.9 release).

0.10 roadmap:
* Replace logging library from `logrus` to `uber-go/zap`. Remove reopen by HUP and inotify. Add periodic logfile changed check
* Move /usr/local/bin/go-carbon to /usr/bin/go-carbon
* Set config paths to `/etc/go-carbon/go-carbon.conf`, `/etc/go-carbon/storage-schemas.conf`, `/etc/go-carbon/storage-aggregation.conf`
* Add systemd service file

I do not like to include log rotation logic into package. But I still think about it

**Comment by mgrzybek** [comment]
I have pushed some stuff in my fork. I can create a PR if you want. Fell free to comment: https://github.com/mgrzybek/go-carbon/commit/d0641aeb5f367b8b3c4289c5a3f24cd6e877e025

**Comment by bzed** [comment]
I'll happily handle the systemd service integration in the debian packaging, but please merge the changes from @mgrzybek first to avoid double work.

**Comment by blysik** [comment]
Any progress on this?

**Comment by lomik** [comment]
systemd service has been added in 0.10.0 release
