### ISSUE TITLE
Any plans to add relay support?

### ISSUE THREAD

**Issue by ghost** [go-graphite/go-carbon#13]
This project has literally saved us as we push towards 5M metrics per minute. Just curious if you plan to add relay support. We use haproxy today and we can split the data among multiple go-carbon instances but we'd like to send a full copy of the data to another location. 

Thanks for releasing this.

Gary

**Comment by deniszh** [comment]
Sorry for intruding but if Author of go-carbon has no plans to implement
such functionality you can use carbon-c-relay or carbon-ng-relay (just
google or search GitHub for links)
Both of them are quite fast and compatible with go-Carbon or normal carbon
daemons.

**Comment by lomik** [comment]
I'll probably realize relay. But certainly not in the near future

**Comment by lomik** [comment]
Sorry, relay not planned in this project. Maybe someday in a separate project
