### ISSUE TITLE
Debian package building fails  due to git vet

### ISSUE THREAD

**Issue by bzed** [go-graphite/go-carbon#133]
There is no issue tracker for your go-whisper fork, so I'm opening the bug here.

```
find . -not -path "*vendor*" -name "*.go" | rev | cut -d/ -f2- | rev | cut -d/ -f2- | sort -u | xargs -IMODULE go vet github.com/lomik/go-carbon/MODULE
_vendor/src/github.com/lomik/go-carbon/carbonserver/carbonserver_test.go:91: github.com/lomik/go-carbon/vendor/github.com/lomik/go-whisper.TimeSeriesPoint composite literal uses unkeyed fields
```

**Comment by lomik** [comment]
Hi. Please, specify golang version.

**Comment by lomik** [comment]
I can't reproduce problem. But this change should fix it https://github.com/lomik/go-carbon/commit/e364c88539d09607fd9f6f254b68dca8a73a77e0

**Comment by bzed** [comment]
go version go1.7.3 linux/amd64

**Comment by bzed** [comment]
And yes, the change fixes the issue. Thanks!
