### ISSUE TITLE
Replicated data?

### ISSUE THREAD

**Issue by devney** [go-graphite/go-carbon#137]
Hi,
Does go-carbon support data replication like carbon-cache's REPLICATION_FACTOR ?  
I am looking to build a completely HA graphite cluster, which means the metric data must be duplicated as well.
Is there a doc or howto showing the process?

--m.

**Comment by lomik** [comment]
go-carbon does not support relay features of carbon-cache. As relay you can use external service - carbon-relay-ng or carbon-c-relay

Сluster scheme in sufficient detail described here: https://github.com/lomik/go-carbon/issues/130#issuecomment-270866633
