### ISSUE TITLE
High Disk IO after migration from graphite

### ISSUE THREAD

**Issue by ghost** [go-graphite/go-carbon#138]
Hello,

I migrated my one year old graphite installation to a new system and use go-carbon as a replacement for the graphite / carbon stack.
Everything is running wonderful, but I see that the disk IO is very high on the new system.

Since I switched from a system with SSDs in a Software RAID 1 to SSDs in a Hardware RAID 10, in my point of view the IO usage should be better, but actual I use more then 80% of my IO reserves.

![image](https://cloud.githubusercontent.com/assets/13642741/22523021/2eb7a8e6-e8be-11e6-916b-a92f5f6bb1f4.png)

Since I found no issue in the config of go-carbon and in the settings of the OS, I would very pleased if someone can look to my config and hopefully see my mistake.

Config: https://gist.github.com/alexanderlauster/0f116b3e71b9780b085f4e2fa58b7e4b

Thanks

**Comment by redbaron** [comment]
it is capable of pushing lots of writes to disk system, hence higher IO utililization. If less IO is made,then more data is kept in ram. check README.md for tunables to adjust that

**Comment by ghost** [comment]
Thx for the reply, I found one reason for the IO problems:
I installed the system on BTRFS; but since the deactivation of COW on the folder with the whisper-files, the disk IO goes down to about 65 %

![image](https://cloud.githubusercontent.com/assets/13642741/22541064/4ddd2a14-e924-11e6-9cdf-1c34202f6fb5.png)

@redbaron What do you mean exactly?

**Comment by deniszh** [comment]
@alexanderlauster ,
Do you using sparse files? What is your write-strategy ? Do you using VM tunings as README suggesting?
It will be better if you show your config here.
Try to experiment with write-strategy (try 'noop'),  try to limit  'max-updates-per-second' to max iops which your hw can handle.

**Comment by ghost** [comment]
No, I'm currently not using sparse files.
The write-strategy is noop, like on the old installation.
VM tunings are active as in the README mentioned.

I played with my config and updated the gist of it:
https://gist.github.com/alexanderlauster/0f116b3e71b9780b085f4e2fa58b7e4b
I set the max-updates-per-second to the calculated iops the RAID 10 should be able to handle; but I will now reduce it step by step.

**Comment by deniszh** [comment]
IMO 100K iops is too much. How many (and which) disks do you have?
Do you monitor your stats? How many metrics are coming per minute?

**Comment by redbaron** [comment]
@alexanderlauster if every update operation produces IO request, then VM tuning is wrong, by default go-carbon doesn't fsync every write for a good reason. Whole idea is to keep data in page cache as much as possible.

formatting xfs with 512 bytes block size helps not to waste memory too

**Comment by ghost** [comment]
So, after some option tests, I found with your help the config settings to get the IO under 40%.
Thanks a lot for your help.

(I updated the gist with the final config)

**Comment by deniszh** [comment]
Just out of curiosity, @alexanderlauster - did you change any VM tuning or only config?
