### ISSUE TITLE
go-carbon does not stop gracefully and loss cache data

### ISSUE THREAD

**Issue by AlexAkulov** [go-graphite/go-carbon#14]
Я думаю процесс остановки должен происходить следующим образом:
1. Перестать принимать метрики. Закрыть соединения и освободить порты. Релей который стоит перед go-carbon, какое-то время сможет выполнять роль кэша. 
- Записать все данные из кэша, игнорируя настройку max-updates-per-second
- Выйти.

Планируется такое реализовать?

**Comment by lomik** [comment]
Можно реализовать такое поведение по, например, сигналу USR1. Я подумаю над этим.

Вообще я хотел сделать reload конфига без остановки приема метрик, но это затянулось на неопределенное время.

**Comment by i19** [comment]
English ?

**Comment by drawks** [comment]
@i19 The above seems to be a suggestion by @AlexAkulov  that go-carbon should have a behavior by which it closes the listening port and flushes the cache to disk without obeying max-updates-per-second throttles on shutdown. @lomik then responds that such a behavior should/could be implemented by having the daemon receive a signal, USR1.

It is worth noting that @lomik is not, AFAICT, a native English speaker and perhaps requests for translations should be worded a bit more politely.

**Comment by i19** [comment]
@drawks Thanks a lot for your translations.
And I do feel sorry for my behaviour, it's not the right way to ask for help.

**Comment by lomik** [comment]
In master:
Grace stop on `USR2` signal: 
- Close all socket listeners (tcp, udp, pickle, carbonlink, pprof http server)
- Disable `max-updates-per-second`
- Flush cache to disk
- Stop daemon

**Comment by AlexAkulov** [comment]
Красота, спасибо!
