### ISSUE TITLE
Replacing whisper with levelDB

### ISSUE THREAD

**Issue by bzed** [go-graphite/go-carbon#145]
Hi,

I was playing with the idea to replace the whisper code with a levelDB backend. I doubt that I will have the time to look into that soon, but maybe other people are interested to work on such a project?

In general to make such tasks easier it would be nice to have the storage backend as a plugin in the code so it is easier to replace it.  Right now there are whisper related pieces all over the code.

Thanks for your input,
Bernd

**Comment by lomik** [comment]
LevelDB was used as storage engine in older versions of InfluxDB.  I recommend starting by studying their experience

Links:
https://www.influxdata.com/benchmarking-leveldb-vs-rocksdb-vs-hyperleveldb-vs-lmdb-performance-for-influxdb/
https://docs.influxdata.com/influxdb/v0.9/concepts/storage_engine/

**Comment by lomik** [comment]
Different storages require different approaches. It's unreasonable to develop a common solution based on go-carbon.

I will return to the problem only if there is a good candidate for the replacement of a whisper. May be for ceres. LevelDB is not good candidate.
