### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by bodsch** [go-graphite/go-carbon#152]
I will just build the go-carbon from source.
But i can't

```
git clone https://github.com/lomik/go-carbon.git
cd go-carbon
make submodules
make
go build  github.com/lomik/go-carbon
# github.com/lomik/go-carbon/carbonserver
_vendor/src/github.com/lomik/go-carbon/carbonserver/carbonserver.go:1378: unknown http.Server field 'IdleTimeout' in struct literal
make: *** [Makefile:7: go-carbon] Error 2
```
i could not find a solution. :(

`go version go1.7.3 linux/amd64`

**Comment by Civil** [comment]
IdleTimeout was introduced in Go 1.8. Please update your golang version to 1.8+

If for some reason you can't do that, you can remove line 1378, though in that case you'll loose control over idle timeout for persistent connections.

**Comment by bodsch** [comment]
okay.
thanks for you fast reply! :)

i think .. a minimum requirement section would be helpful. :'D

**Comment by lomik** [comment]
Minimum section added :D
https://github.com/lomik/go-carbon/commit/e0fae152afccbc0133fb7babe48c4f708456f639
