### ISSUE TITLE
Static binary release

### ISSUE THREAD

**Issue by kkopachev** [go-graphite/go-carbon#162]
I noticed you have rpm and deb packages available on [releases](https://github.com/lomik/go-carbon/releases) page. Would it be possible to also provide statically built linux amd64 binary? Useful for easy inclusion into docker images.

**Comment by lomik** [comment]
Yes, it is possible. May be in 0.10 release.

**Comment by lomik** [comment]
Static binary has been provided in 0.10.0 release
