### ISSUE TITLE
notConfirmedShard* metrics -- what do they mean?

### ISSUE THREAD

**Issue by halcyonardency** [go-graphite/go-carbon#166]
Hello. Trying to debug some interesting queuing we are seeing.  

What do these metrics means?

notConfirmedShardUsedMax 
notConfirmedLenTotal
notConfirmedShardLenMax
notConfirmedUsedTotal

notConfirmedShardUsedMax  means total shards in use..?  Are any of these indicators where we'd want to bump up working or threads?

**Comment by halcyonardency** [comment]
Also, the documentation says the write_strategy option for timestamp sorted flushing is "sorted" but it looks like the code is looking for string "sort" instead? I'm a little confused if I should be using "sorted" or "sort" or if they both work.

```
# Limit of in-memory stored points (not metrics)
max-size = 1000000
# Capacity of queue between receivers and cache
# Strategy to persist metrics. Values: "max","sorted","noop"
#   "max" - write metrics with most unwritten datapoints first
#   "sorted" - sort by timestamp of first unwritten datapoint.
#   "noop" - pick metrics to write in unspecified order,
```

https://github.com/lomik/go-carbon/blob/master/cache/cache.go#L89

**Comment by lomik** [comment]
I've added notConfirmed* metrics for debug and forgot to remove. Fixed here https://github.com/lomik/go-carbon/commit/e5a68b02394c6532f65971e3df0182bc95b663bd

**Comment by lomik** [comment]
>Also, the documentation says the write_strategy option for timestamp sorted flushing is "sorted" but it looks like the code is looking for string "sort" instead? I'm a little confused if I should be using "sorted" or "sort" or if they both work.

Fixed here https://github.com/lomik/go-carbon/commit/a46804af182f2dedc5abd1d5e65b2e3ba298cf46

Thanks for bug report!
