### ISSUE TITLE
input-buffer still in use?

### ISSUE THREAD

**Issue by halcyonardency** [go-graphite/go-carbon#167]
In the reference config "input-buffer" is still listed, but I don't see this in the codebase.  Is this variable still in use?

If so, can I track it's utilization with one of the metrics?  What does it do?

https://github.com/lomik/go-carbon/blob/master/conf-examples/carbon.conf#L20

**Comment by lomik** [comment]
Sample in conf-examples is not actual. Please, see configuration section in README.md https://github.com/lomik/go-carbon#configuration 

In next version sample config and readme.md will be unified. You can find actual sample config for  master here https://github.com/lomik/go-carbon/blob/new-deploy/deploy/etc/go-carbon.conf

**Comment by halcyonardency** [comment]
okay cool. thanks for the info!  we still have this value in our config from old versions -- we'll likely remove it with our next major update.
