### ISSUE TITLE
NaN values being saved in Whisper datafiles

### ISSUE THREAD

**Issue by xneo64** [go-graphite/go-carbon#17]
hi @lomik , With reference to https://bugs.launchpad.net/graphite/+bug/867882

Somehow I'm finding my whisper files to contain `nan`, and while this is valid from a python JSON spec, it's breaking the Grafana javascript code which parses the JSON from graphite. And causes an error and does not plot graphs. 

Apparently carbon-cache was patched to eliminate such cases of writing nan to the whisper files. Can you look into this?

**Comment by xneo64** [comment]
to further illustrate, here's an example of the cpu data gathered from collectd. This data is replicated and pushed to two hosts, one runs go-carbon, and the other carbon-cache:

with go-carbon gives the below two occurrences:
`whisper-dump.py /home/graphite/storage/dc1/apphost00/cpu/0/cpu/interrupt.wsp | grep nan`
`0: 1446541000,        nan`
`0: 1446540960,        nan`

while with carbon-cache no `nan` is found in `.wsp` files. Looking up these timestamps in carbon-cache's wsp files, they're not to be found. It seems that the default behaviour here is to drop any write to whisper containing 'nan'

**Comment by xneo64** [comment]
hello again @lomik i was able to achieve this by adding the below condition in `whisper.go` before the write happens:

``` go
if !math.IsNaN(r.Value) {
    points[i] = &whisper.TimeSeriesPoint{Time: int(r.Timestamp), Value: r.Value}
}
```

naturally, in the beginning I also had to define importing of `math`

**Comment by ahayworth** [comment]
We are experiencing the same bug in production. Pull #27 fixes it (with tests, too!).

:heart:
