### ISSUE TITLE
Frequent carbonlink errors

### ISSUE THREAD

**Issue by johnseekins** [go-graphite/go-carbon#18]
I am seeing a number of errors similar to the following:

[2015-11-19 13:56:51] D [carbonlink] read carbonlink request from 127.0.0.1:32800: Can't read message length: read tcp 127.0.0.1:7002->127.0.0.1:32800: i/o timeout
[2015-11-19 13:56:51] D [carbonlink] read carbonlink request from 127.0.0.1:32998: Can't read message length: read tcp 127.0.0.1:7002->127.0.0.1:32998: i/o timeout

I _assume_ this is my fault. Can you guide me any on how to fix this issue?

**Comment by automatedops** [comment]
I am getting same error. @johnseekins Have you fix this ?

**Comment by johnseekins** [comment]
I have not. For the most part, I've just been ignoring them since my
install is small enough I don't completely need the carbonlink data.
Are you also running graphite-web 0.9.15?

**Comment by automatedops** [comment]
No, I am trying to use [Graphite API 1.1.2](https://github.com/brutasse/graphite-api) instead of Graphite Web.

**Comment by lomik** [comment]
This is not error and not problem, error level is "debug". go-carbon closing old unused connections from graphite-web after 30 seconds timeout.

**Comment by lomik** [comment]
Set `log-level = "info"` and forget about this message :)

**Comment by johnseekins** [comment]
That's certainly a solution...
But maybe you could make the message a little more clear? Perhaps don't tag it as an error in the log?

**Comment by johnseekins** [comment]
Excuse me...it isn't tagged as an error. But maybe the message could say something about disconnecting, rather than simply "i/o timeout".
