### ISSUE TITLE
initscript: /var/lock/subsys directory can be missing

### ISSUE THREAD

**Issue by Farfaday** [go-graphite/go-carbon#181]
Hi,
I tried today updating to last version 0.10.0.

I got following error when starting/restarting daemon on Ubuntu Trusty:

_Starting daemon go-carbon : touch: cannot touch ‘/var/lock/subsys/go-carbon’: No such file or directory [FAILED]_

After doing  _# mkdir /var/lock/subsys_ the error was gone.
I guess this is related to https://github.com/lomik/go-carbon/commit/05fbeb3d882d4392e0068f8b4cbd603a41d4e844

Thanks !
François

**Comment by lomik** [comment]
lockfile is not used. I forgot to remove it from init script. 
It will be removed in next release

**Comment by lomik** [comment]
Released in 0.10.1
