### ISSUE TITLE
Unable to pickle long values

### ISSUE THREAD

**Issue by Glandos** [go-graphite/go-carbon#182]
According to my tests, the following data cannot be read by go-carbon:
`[('hostname.interface-eth_lan2.if_octets.rx', (1498059235, 9087827L))]`
However, the following data is unpickled without errors:
`[('hostname.interface-eth_lan2.if_octets.rx', (1498059235, 9087827))]`

I'm using `protocol=2` when pickling.

I would expect go-carbon to be able to unpickle long values.

**Comment by lomik** [comment]
I have fixed this problem in master. You can build new binary from source or wait several days for next release. 

Thanks for the report!

**Comment by lomik** [comment]
Released in 0.10.1

**Comment by Glandos** [comment]
It's always nice to see a really fast reaction time 👍
