### ISSUE TITLE
Add carbon protobuf receiver

### ISSUE THREAD

**Issue by Glandos** [go-graphite/go-carbon#184]
I've made the switch from `carbon-cache` to `go-carbon`, mainly because it gives the opportunity to use [carbonapi](https://github.com/go-graphite/carbonapi) which is wayyyy simpler to manage than [graphite-web](https://github.com/graphite-project/graphite-web) or wayyyy faster than [graphite-api](https://github.com/brutasse/graphite-api).
If I understand correctly, one of the reason for this speed is the use of protobuf between go-carbon and carbonapi.
I've read recently that `carbon-cache` added a [protobuf](https://github.com/graphite-project/carbon/commit/3bd8c75a80e37bbab4565c3f32d1a36ad449ddd6) protocol.

What do you think of adding this as a receiver? Can the receiver get even better performance?

**Comment by lomik** [comment]
Hi, I'm going to add protobuf receiver in the near future. But I doubt that it will be much faster than the plain protocol

**Comment by Civil** [comment]
@Glandos you'll get one extra problem with protobuf receiver - you'll need to write custom relay that supports protobuf :)

**Comment by lomik** [comment]
Protobuf protocol has been added in master. Sample config:
```
[receiver.protobuf]
listen = ":2005"
protocol = "protobuf"
```

**Comment by Glandos** [comment]
@Civil yes, but in my case, I have no relay, because everything is on the same host. So yes, maybe performance increase will be invisible anyway…

@lomik thanks!

**Comment by lomik** [comment]
Released in 0.11.0
