### ISSUE TITLE
Setting Points per Update

### ISSUE THREAD

**Issue by Farfaday** [go-graphite/go-carbon#187]
Hi,
we are receiving about 10K metrics per seconds on our go-carbon hosts.
We had max-updates-per-second = 0 and our disk utilisation was really high.
The carbon.agents.$Cache.persister.pointsPerUpdate metric was most of the time 1.
The recommanded os tuning part from the readme (https://github.com/lomik/go-carbon#os-tuning) is already in place, write-strategy = "noop"

We then set max-updates-per-second = 2000 to "force" the pointsPerUpdate to be about 5.
This worked as expected. Disk utilisation was considerably lowered, and the cache is now better used.

But I am not sure this is really a good way to force go-carbon doing "bigger" whisper update operation, reducing IO load. 
Is there a better parameter to set into the config for that ? 

Many thanks !

**Comment by deniszh** [comment]
Limiting of max-updates-per-second is exactly a recommended way to lowering disk load and raising PPU. Not sure if go-carbon has another parameter for that.

**Comment by Farfaday** [comment]
okay!
But what if the amount of incoming metrics suddenly increases to, say, 100k metrics per second (so a 10x factor) ? Or x100 ?

**Comment by deniszh** [comment]
Then metrics will be cached in the cache. If your cache is too small - then it will overflow and you start to loose metrics.
Go-carbon is a nice software but all software has limitations.

**Comment by deniszh** [comment]
You can use Clickhouse-based setup -  https://github.com/lomik/carbon-clickhouse + https://github.com/lomik/graphite-clickhouse. It has no cache and sending metrics directly to CH.
