### ISSUE TITLE
Install issues 

### ISSUE THREAD

**Issue by pavel-odintsov** [go-graphite/go-carbon#19]
Hello!

Thanks for nice toolkit!

I have installed it on Ubuntu 14.04 and got following message:

``` bash
sudo dpkg -i go-carbon_0.6_amd64.deb 
Выбор ранее не выбранного пакета go-carbon.
(Чтение базы данных … на данный момент установлен 85491 файл и каталог.)
Preparing to unpack go-carbon_0.6_amd64.deb ...
Unpacking go-carbon (0.6) ...
Настраивается пакет go-carbon (0.6) …
2015/11/23 23:03:23 open /data/graphite/schemas: no such file or directory
Processing triggers for ureadahead (0.100.0-16) ..
```

Looks like you need to change path to standard :)

**Comment by pavel-odintsov** [comment]
So I have one suggestion here. 

What about something like this if customer already have graphite:

``` bash
sudo cp /etc/carbon/storage-schemas.conf  /data/graphite/schemas
```

Also will be fine to add default version of schemas.conf to package.

**Comment by lomik** [comment]
Path changing roadmap https://github.com/lomik/go-carbon/issues/128#issuecomment-262749739
