### ISSUE TITLE
Debian package: UID user carbon

### ISSUE THREAD

**Issue by Farfaday** [go-graphite/go-carbon#190]
Hi,
currently, the carbon user created by the Debian package is over 1000. (It is created by https://github.com/lomik/go-carbon/blob/master/deploy/before_install.sh)

Reading https://www.debian.org/doc/debian-policy/ch-opersys.html#s9.2 , and as the carbon user - if i understood correctly - is a system user, the proposed option **--system** for the **adduser** command should be used in the before_install.sh file.

Many thanks !

**Comment by lomik** [comment]
Released in 0.11.0
