### ISSUE TITLE
Remote storage for go-carbon

### ISSUE THREAD

**Issue by ushacow** [go-graphite/go-carbon#191]
Hi! I'm figuring out a possibility of configuration go-carbon with remote whisper storage (two separate docker containers to be exact). But in this case I should point a storage dir with whisper in configuration file which can be only local. So should I place go-carbon and whisper on the same container? Or there is some other option?

**Comment by deniszh** [comment]
Whisper is a local storage, you can't use it remotely. In case of Docker
you can use volumes to mount whisper storage from different container (but
it should be local, though).
Also, Docker philosophy allow to put more than one process in container,
so, you can build container with multiple processes, like go-carbon,
carbonapi and grafana, for example.
Or you can use carbon-clickhouse instead - it will use Clickhouse server as
a storage, which could be running in separate container on different host.

**Comment by ushacow** [comment]
Thank you so much! Yes, mounting shared storage is ok. My goal is to make graphite deployment as flexible as possible and the components are insulated and easily replaceable. So I am going to create two containers, one with graphite-web and the second one with go-carbon and whisper.
