### ISSUE TITLE
persister test fails on virtual machine

### ISSUE THREAD

**Issue by lazyfrosch** [go-graphite/go-carbon#203]
I tried building go-carbon on CentOS 7 in a VirtualBox vm, the test below fails.

When I build it in a chroot/Docker container with CentOS 7 under my main kernel it works.

Is this due to limited resources, or a kernel issue?

Host: `Linux debian-stretch 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
` \
CentOS VM: `Linux centos7 3.10.0-693.2.1.el7.x86_64 #1 SMP Wed Sep 6 20:06:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

```
+ go test github.com/lomik/go-carbon/persister
--- FAIL: TestThrottleChan (5.00s)
        Error Trace:    throttle_test.go:40
	Error:		Should be true
	Messages:	perSecond: 1000, bw: 841
		
FAIL
FAIL	github.com/lomik/go-carbon/persister	5.300s
```

**Comment by lomik** [comment]
I've seen this in travis-ci.
This is problem of limited resources. Just ignore it.
