### ISSUE TITLE
Bad load balancing between CPU cores

### ISSUE THREAD

**Issue by artful88533** [go-graphite/go-carbon#212]
Hello!
I have poblem with balancing between CPU cores:
<img width="1419" alt="screen shot 2017-11-19 at 7 11 11 pm" src="https://user-images.githubusercontent.com/19188399/32993307-da916492-cd5e-11e7-85b0-e8b200e1d909.png">
When I increase traffic the one process overload and graphs is interrupted in grafana:
<img width="1404" alt="screen shot 2017-11-19 at 7 13 36 pm" src="https://user-images.githubusercontent.com/19188399/32993266-370e4358-cd5e-11e7-9139-4512cd740e50.png">

Server:
CPU: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
Memory: 256 GB
Disk: SSD

Go-carbon config:
```
[common]
user = "_graphite"
graph-prefix = "carbon.agents.{host}"
metric-endpoint = "local"
metric-interval = "1m0s"
max-cpu = 11

[whisper]
data-dir = "/var/lib/graphite/whisper"
schemas-file = "/etc/go-carbon/storage-schemas.conf"
aggregation-file = "/etc/go-carbon/storage-aggregation.conf"
workers = 22
max-updates-per-second = 0
sparse-create = false
enabled = true

[cache]
max-size = 1000000000
nput-buffer = 100000000
write-strategy = "noop"
```

What I do wrong? Please help me using all CPU resources.

**Comment by deniszh** [comment]
@artful88533 : try to experiment with `max-cpu` and `workers` settings. Please note that  E5-1650 v3 have only 6 physical cores and hyperthread core is not the same as normal core. Also 22 workers can be too much too.
E.g. try `max-cpu = 8` and `workers = 8`.
What do you have in logs for go-carbon? According to graphs during peak time you have spike of tcp errors.

**Comment by artful88533** [comment]
added `max-cpu = 8` and `workers = 8`
I don't see any changes.

In log:
```
[2017-11-19T18:04:29.263Z] WARN [tcp] failed to accept connection {"error": "accept tcp [::]:2003: accept4: too many open files"}
[2017-11-19T18:04:29.262Z] ERROR [persister] failed to open whisper file {"path": "/var/lib/graphite/whisper/production/unicorn24/controllers/runtime/ads_controller/show/db_runtime.wsp", "error": "open /var/lib/graphite/whisper/production/unicorn24/controllers/runtime/ads_controller/show/db_runtime.wsp: too many open files"}
[2017-11-19T18:04:29.262Z] ERROR [persister] failed to open whisper file {"path": "/var/lib/graphite/whisper/production/unicorn21/controllers/ads_controller/finish.wsp", "error": "open /var/lib/graphite/whisper/production/unicorn21/controllers/ads_controller/finish.wsp: too many open files"}
[2017-11-19T18:04:29.263Z] WARN [tcp] failed to accept connection {"error": "accept tcp [::]:2003: accept4: too many open files"}
```

My OS settings
cat /etc/security/limits.conf

```
*                hard    nproc           950000
*                soft    nproc           950000
*                soft    nofile          950000
*                hard    nofile          950000
root             soft    nofile          950000
root             hard    nofile          950000
_graphite        soft    nofile          950000
_graphite        hard    nofile          950000
```

ulimit -a
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1031262
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 950000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1031262
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by deniszh** [comment]
Hmmm... Are you really consuming 950 000 open files? That's very odd.
You can check real limits for your process running `cat /proc/<PID>/limits`, where <PID> - pid of go-carbon process, maybe your limits are not working.
How many clients (tcp clients for go-carbon) do you have?

**Comment by deniszh** [comment]
You can also get real number of open files running `lsof -p <PID> | wc -l`

**Comment by artful88533** [comment]
The problem was in supervisor :) I didn't know about `minfds` parameter in supervisor config. After set it all works fine! Thank You very much!

**Comment by artful88533** [comment]
All work but still one process is more loaded. I don't know it is problem or not.
<img width="1427" alt="screen shot 2017-11-19 at 9 37 04 pm" src="https://user-images.githubusercontent.com/19188399/32994566-d8108744-cd71-11e7-8c0a-aa2b94949bb9.png">

**Comment by deniszh** [comment]
>The problem was in supervisor :) I didn't know about minfds parameter in supervisor config. After set it all works fine! Thank You very much!

You're welcome!
Yep, that's known thing for `supervisord`, indeed.

>All work but still one process is more loaded. I don't know it is problem or not.

I also noticed that one process is always more loaded, but I didn't get any problems with it. `go-carbon` is quite capable software. :)

**Comment by lomik** [comment]
maybe more loaded core is used for "receiver". go-carbon uses one goroutine for all udp and one goroutine per tcp connection.  some relays (carbon-c-relay) send all traffic via single tcp connection
