### ISSUE TITLE
cannot load TOML value of type string into a Go integer {}

### ISSUE THREAD

**Issue by AlViKl** [go-graphite/go-carbon#215]
Hello.

I've a problem with kafka.receiver, when  uncomment fetch-interval and reconnect-interval. In config file this variables  was set as:
...
reconnect-interval = "5m"
...
fetch-interval = "200ms"
...
And, when I started go-carbon, logs contain this message:
FATAL [main] toml: cannot load TOML value of type string into a Go integer {}

Observe the sources in receiver/kafka/kafka.go:	

    StateSaveInterval time.Duration `toml:"state-save-interval"`
	ReconnectInterval time.Duration `toml:"reconnect-interval"`
	FetchInterval     time.Duration `toml:"fetch-interval"

and in go-carbon/carbon/config.go for the same variable by type, which works correctly:

	ReadTimeout             *Duration `toml:"read-timeout"`
	IdleTimeout             *Duration `toml:"idle-timeout"`

Can you fix this so that the go-carbon can starts with the parameters fetch-interval and reconnect-interval in kafka.receiver?

**Comment by lomik** [comment]
Already fixed in master (and 0.12.0-rc1). Will be released in 0.12.0
