### ISSUE TITLE
Support pickle format from dropwizard/metrics

### ISSUE THREAD

**Issue by pwielgolaski** [go-graphite/go-carbon#216]
I noticed that metric sent from dropwizard in pickle format are not understood.

https://github.com/dropwizard/metrics/blob/4.0-development/metrics-graphite/src/main/java/com/codahale/metrics/graphite/PickledGraphite.java#L290

All because it passes values as String not Float.
Do you think we could start to accept string as well?

I noticed it require tiny change here:
https://github.com/lomik/graphite-pickle/blob/master/types.go#L100
```
	case string:
		v, _ := strconv.ParseFloat(value, 64)
		return v, true
```

Here is sample for format from dropwizard/metric
`(l(S'param1'\n(L1423931224L\nS'60.2'\ntta.`

**Comment by lomik** [comment]
Thanks for the sample!
Support was added in master.
