### ISSUE TITLE
proper way to shutdown on receiver error?

### ISSUE THREAD

**Issue by joemiller** [go-graphite/go-carbon#223]
I'm hunting a potential issue with one of my consumers. I've observed two instances where it stopped consuming messages from google pubsub. I have not actually found an error message however, so I'm not positive on the cause yet.

One of my suspicions is that the receiver may return an error and stop processing, but the go-carbon process continues on. If this is the case, I'm wondering what the proper way to handle errors here would be:

(1) Gracefully shutdown go-carbon (my supervisor would restart it)? If so, what is the proper way to do this? I looked at the http and kafka receivers for a hint but could not find one.

(2) the receiver should never try to exit, and instead I should wrap the subscription.Receive() call in a for loop so that it tries to start receiving again after encountering an error?

https://github.com/lomik/go-carbon/blob/master/receiver/pubsub/pubsub.go#L128-L136
```
	go func() {
		err := rcv.subscription.Receive(cctx, func(ctx context.Context, m *pubsub.Message) {
			rcv.handleMessage(m)
			m.Ack()
		})
		if err != nil {
			rcv.logger.Error(err.Error())
		}
		close(rcv.closed)
```

**Comment by lomik** [comment]
Receiver can stop go-carbon only from init function (config validation or bind error). If receiver is inited it should work forever (until Stop called). 

You should log error and resubscribe (preferably with timeout).

**Comment by joemiller** [comment]
@lomik thanks, i'll go that route.
