### ISSUE TITLE
Losing data from 3 - 4AM UTC every day

### ISSUE THREAD

**Issue by lindsaylandry** [go-graphite/go-carbon#236]
I have noticed that, from 3AM to around 4AM UTC, go-carbon is doing a massive read of the filesystem. IOPS on this machine is relatively small, and there is about 1,000,000 files worth of data. So when go-carbon is doing this read, CPU-wait goes way up, and I lose about 40% of data that should be aggregated by carbon-relay-ng.

Using go-carbon 0.12.0 on ubuntu 14.04.

What is go-carbon doing at this time? Is there a way to turn this off so I don't lose data?

**Comment by piotr1212** [comment]
Sounds more like an issue with your system. Is it a VM? Got any backup or snapshotting running around that time, other scheduled IO heavy jobs? What storage does it write to?

**Comment by azhiltsov** [comment]
on top of what piotr1212 said:
If you using carbonserver+trigram then it scans all whisper directories frequently
```
[carbonserver[
trigram-index = true
scan-frequency = "5m0s"
```
this might interfere with some log rotation on the host/vm and make it visible for you, while other times passes unnoticed.

**Comment by lindsaylandry** [comment]
Ok then it's probably something we are doing on our end. I just wanted to make sure go-carbon itself wasn't doing anything special at that time. I think it might be related to nightly test suites.

We had to turn trigram-index to false since it didn't allow carbonapi to query for wildcards. Scan frequency is still at 5m0s

**Comment by agent462** [comment]
@lindsaylandry If this is not solved make sure it's not https://linux.die.net/man/8/updatedb trying to create an index/db for every .wsp file.

**Comment by lindsaylandry** [comment]
@agent462 I did turn off mlocate because that was causing missing data too. I think the problem was a large inflow of data at once due to nightly test suites, so closing this.
