### ISSUE TITLE
go-carbon service crashing due to too many metrics created

### ISSUE THREAD

**Issue by nayanashettyft** [go-graphite/go-carbon#239]
Hi,
We are currently using the python carbon graphite servers for pushing metrics and are building an equivalent if not better go-carbon servers (to improve the performance)
We are pushing close to 1.5M metrics/second.
Most of our testing so far has gone really well. However we have now hit an issue.
We have some systems pushing ~5k new metrics all at a particular point in the day, everyday. The gocarbon service seems to be crashing on receiving this. From what we can see, the python-carbon is able to handle this peek because of the MAX_CREATES_PER_MINUTE set to 5000 ie ~83/s.
All documentation we have read so far suggests this is not available in go-carbon. Is this still true? And if so, are there any other work arounds we could play around with?

**Comment by lomik** [comment]
Yes, go-carbon does not support MAX_CREATES_PER_MINUTE. It is possible in current internal architecture but need a little refactoring.
I'll see in the near future how much it is hard

**Comment by lomik** [comment]
It was even easier than I thought. Implemented in "max-creates-per-second" branch. Untested

**Comment by lomik** [comment]
Tested and merged into master

**Comment by nayanashettyft** [comment]
you are a star. Thanks a lot of the quick turn around. We will try this out on Monday. Is it possible to create a release please so that we dont have to change the way we download the package.

**Comment by nayanashettyft** [comment]
We have tested the load we are getting with the max_creates_per_second set and the system is performing much better than before. We dont see any crash. However due to the number of creates and updates and memory utilisation we have moved to a EC2 instance that can handle more as well

**Comment by lomik** [comment]
released in 0.13.0
