### ISSUE TITLE
Build fails with "func literal" error

### ISSUE THREAD

**Issue by MikeKirkFT** [go-graphite/go-carbon#240]
Trying to build RPMs for testing latest updates and getting an error relating to Go context module during gox-build step of Makefile (see below). Apologies if this is not the correct process or designed for end-user usage. Steps to repeat 

- cd deploy/buildenv
- ./build.sh 

Tried with the default 1.8.3 and 1.10.1 versions of Go. 

```
Successfully tagged go-carbon-build:latest
+ cd /src/go-carbon/
+ make gox-build
rm -rf build
mkdir -p build
cd build && go build github.com/lomik/go-carbon
# github.com/lomik/go-carbon/receiver/pubsub
../_vendor/src/github.com/lomik/go-carbon/receiver/pubsub/pubsub.go:133: cannot use func literal (type func("context".Context, *"github.com/lomik/go-carbon/vendor/cloud.google.com/go/pubsub".Message)) as type func("github.com/lomik/go-carbon/vendor/golang.org/x/net/context".Context, *"github.com/lomik/go-carbon/vendor/cloud.google.com/go/pubsub".Message) in argument to rcv.subscription.Receive
Makefile:44: recipe for target 'gox-build' failed
make: *** [gox-build] Error 2
```

**Comment by lomik** [comment]
go 1.10.3 works fine. Dockerfile updated https://github.com/lomik/go-carbon/commit/57829e26737509cbe974cf450beb1b9f46331048

**Comment by MikeKirkFT** [comment]
Hey thanks, that's sorted for me now.
