### ISSUE TITLE
Whisper updates not correct with many points in cache

### ISSUE THREAD

**Issue by dforste** [go-graphite/go-carbon#25]
This is pretty much a continuation to this issue: https://github.com/grobian/carbon-c-relay/issues/123 
Currently we keep a large cache around because the writes are getting cached by the OS and causing all services on the box to grind to a halt. We currently do 19 points per update and 3000 updates per minute. 

I have a whisper file setup with two archives: 
10s:1m 
1m:2y 

These are configured to aggregate by sum. When end result data points should be the same they are not. When only one archive is used there does not seem to be an issue.

**Comment by lomik** [comment]
Can you give a sample of input data (example, from tcpdump)? And aggregation/schemas configs
Read wsp file with whisper-dump tool. What you see? And what expected?

**Comment by dforste** [comment]
I expected graphs that should have identical data. These do not seem to. 

If you want to test try this as a minimal test. If it does not reproduce results you can try scaling up until you have 600,000 in your cache at any one time. 

storage-schema.conf

```
[app]
pattern = ^app\.
retentions = 10s:5m,1m:60d 
```

storage-aggregation.conf 

```
[01_app_count]
pattern = \.count.*$
xFilesFactor = 0.01
aggregationMethod = sum
```

gocarbon.conf

```
max-updates-per-second = 1
```

Then send metrics every 10 seconds so that 20 points are in each update. 
60 seconds \* 20 points per update.  = 1200 per minute
120 metrics every 10 seconds. 

Some python 2.7 code to generate the metrics: 

``` python
def send_metrics (count, host, port, test):
  s = socket()
  s.connect( (host,port) )
  now = int(time.time())
  for i in xrange(0, count):
    metric = test
    value = 10
    s.sendall('%s %s %s\n' % (metric, value, now))
    count += 1
#  print 'sent %d metrics in %d seconds.' % (count, int(int(time.time()) - now))

host = 'localhost'
port = 2003
test = 'app.count.'

for minutes in xrange(0, 30) :
  for x in xrange(0, 5) :
    for z in range(0, 120) : 
      import threading
      threading.Timer(x * 10, send_metrics, args=( 1 , host , port , test + str(z) ) ).start()
  time.sleep(60)
```

The above script is of course slightly adapted. Once you run the test verify go-carbon was caching the metrics as they do in my case. If not you may need to scale things up a bit.

**Comment by lomik** [comment]
With retentions "10s:1m,1m:2y" 19 points (from now with interval 10 sec) can't be correct aggregated by sum method. Data points older 1 minute from "now" (save to file time) replace values in "1m:2y" archive without sum with anything.

**Comment by dforste** [comment]
Is this a bug with the go-carbon or go-whisper library?

**Comment by lomik** [comment]
This is not a bug. This is wrong retentions rule.

Archive "10s:1m" can store (and aggregate to "1m:2y") only 6 points. Older points written directly to archive "1m:2y" without aggregation (with rewrite old values). Change retentions rule to "10s:1h,1m:2y" and try again.

Reproducing with python-whisper:

```
import time
import whisper

retentions = map(whisper.parseRetentionDef, "10s:1m,1m:2y".split(","))
whisper.create("test.wsp", retentions, xFilesFactor=0.01, aggregationMethod="sum")

points = []
now = int(time.time())
for i in xrange(-18, 1):
    points.append((now+i*10, 10))

whisper.update_many("test.wsp", points)
```

whisper-fetch test.wsp:

```
1449040200  10.000000
1449040260  10.000000
1449040320  10.000000
1449040380  20.000000
1449040440  None
```

Same with retentions "10s:1h,1m:2y" returns:

```
1449040200  60.000000
1449040260  60.000000
1449040320  60.000000
1449040380  10.000000
1449040440  None
```
