### ISSUE TITLE
FS error 'file name too long' infinitely keeps metric in the go-carbon memory.

### ISSUE THREAD

**Issue by azhiltsov** [go-graphite/go-carbon#258]
When go-carbon receives a metric which can't be flushed on disk it keeps trying infinitely:

`{"level":"ERROR","timestamp":"2018-09-28T17:20:51.120+0200","logger":"persister","message":"failed to open whisper file","path":"/var/lib/carbon/whisper/www/_3DUt4CaZVl5wa1_oTUVkNFYly61NGis_tC_9yKaV_9J1Q89eSvbRHnfE4jOCZB7Fkk1fqj9zFRWKsJenTCL2N1NbvWPFUoGwOzZZ6n6WglIn3j7Tn_6XoMb1vXUCGLpC1lFFfDyKhCk_c0J6FAoYWxXmp3nyc_dOxJsphA9qxzAwsknZHHd0SxK08HV1mdcZamlxJ3_yIu8i98chhc4b1OZvDOqyKGTBBfT33IuMVqO_el0z8LSmpNO31_ScaLBlKY7_Oo1a1tiSJ_EeTFTE9o1fMc6el_D9lXG2oYKu_Hk3dcQAcF33N_P_9_pyzH8syl1TQYmVrUARoyVtutISJyOtclH6GqQCn7cmXLsITQqQMyWHLwrGqAyeDtSaklbfe0YKvtVJ1BGmqZ1ye_l97HyB_uDkVXXsJJSGb7cKzfwKUQq2EiIJRp2iZmk1HT31PO2mBlMbizt01TutzmWb4H_1M_26/login_count.wsp","error":"open /var/lib/carbon/whisper/www/_3DUt4CaZVl5wa1_oTUVkNFYly61NGis_tC_9yKaV_9J1Q89eSvbRHnfE4jOCZB7Fkk1fqj9zFRWKsJenTCL2N1NbvWPFUoGwOzZZ6n6WglIn3j7Tn_6XoMb1vXUCGLpC1lFFfDyKhCk_c0J6FAoYWxXmp3nyc_dOxJsphA9qxzAwsknZHHd0SxK08HV1mdcZamlxJ3_yIu8i98chhc4b1OZvDOqyKGTBBfT33IuMVqO_el0z8LSmpNO31_ScaLBlKY7_Oo1a1tiSJ_EeTFTE9o1fMc6el_D9lXG2oYKu_Hk3dcQAcF33N_P_9_pyzH8syl1TQYmVrUARoyVtutISJyOtclH6GqQCn7cmXLsITQqQMyWHLwrGqAyeDtSaklbfe0YKvtVJ1BGmqZ1ye_l97HyB_uDkVXXsJJSGb7cKzfwKUQq2EiIJRp2iZmk1HT31PO2mBlMbizt01TutzmWb4H_1M_26/login_count.wsp: file name too long"}`

I assume this metric need to be dropped.

**Comment by davidnewhall** [comment]
Is the workaround to restart `go-carbon`?

**Comment by gksinghjsr** [comment]
#266 fixes this. I believe this issue can be closed, unless you are facing this issue with current master.

**Comment by davidnewhall** [comment]
Thanks for the info. We'll upgrade!
