### ISSUE TITLE
Sparse .wsp creation

### ISSUE THREAD

**Issue by pdolan** [go-graphite/go-carbon#26]
Hi there,

Have recently started to use go-cabon on our secondary metric store for benchmark purposes (am quite excited at the prospect of not having to depend on the python caches) - am getting some very promising results so far.

A minor point, based on our tiered storage layout, we get quite tight for space without sparse whisper file creation enabled - is this option something that is on the roadmap for go-cabon?

**Comment by lomik** [comment]
I have no plan to implement sparse creation. I'll see how difficult it is to implement it

**Comment by drawks** [comment]
The syscall package does have a wrapper around the fallocate call which can be used to quickly create sparse file allocations, however, IIRC the actual file creation portion of go-carbon lives in the go-whisper library, so this issue is perhaps in the wrong project.

**Comment by pdolan** [comment]
@drawks Good point - I suspect all that would be required from go-carbon is to expose the usage of that option when(/if!) made available via go-whisper.

@lomik I'll open an issue on go-whisper lib and re-open this issue when the option is available. Many thanks!

**Comment by pdolan** [comment]
@lomik Ah, sorry about this - but it seems your whisper.go version is being bugfixed locally! I suspect this issue may have a better chance of being resolved if left open here :)

**Comment by ctrlok** [comment]
``` go
    remaining := whisper.Size() - whisper.MetadataSize()
+++  whisper.file.Seek(int64(remaining-1), 0)
+++  whisper.file.Write([]byte{0})
    chunkSize := 16384
    zeros := make([]byte, chunkSize)
    for remaining > chunkSize {
        // if _, err = whisper.file.Write(zeros); err != nil {
        //  return nil, err
        // }
        remaining -= chunkSize
    }
    if _, err = whisper.file.Write(zeros[:remaining]); err != nil {
        return nil, err
    }
```

Work fine for me.

**Comment by ctrlok** [comment]
@lomik Hi. It looks like that implementation works fine. How can I inject it into go-carbon? Should I create "pull request" only to go-carbon? Because it depends on https://github.com/lomik/go-whisper/

**Comment by lomik** [comment]
Added in master as new option. But not tested in production %)

**Comment by ctrlok** [comment]
Thanks. I already test it with a huge load. And have plans to use it in our production. 
Just for history. Commits: https://github.com/lomik/go-carbon/commit/3005d12cef55c7742e6438e1b04f5e277da9f4e2 and https://github.com/lomik/go-whisper/commit/a503388ddb0c5cc4f6b0b023cdf2163b8a6f3314
