### ISSUE TITLE
UDP is not consumed when \n is missing

### ISSUE THREAD

**Issue by efficks** [go-graphite/go-carbon#278]
When receiving an UDP metric, go-carbon consider a metric without \n like an incomplete metric.
The plain-text protocol documentaiton of carbon-cache does not mention that the line must ends with a \n (https://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-plaintext-protocol).

I expect go-carbon to supports UDP metric without \n like it's state in the carbon plain text protocol. I have many systems sending metrics without \n.
The problem is probably at this line : https://github.com/lomik/go-carbon/blob/3f1d2c44bb0155e109309bf99f454fc124e10a9c/receiver/udp/udp.go#L166

The issue has been adressed in carbon-relay-ng (https://github.com/graphite-ng/carbon-relay-ng/issues/298) ans they released a fix.

**Comment by lomik** [comment]
Behavior changed in master
