### ISSUE TITLE
can't set retention rate to every second

### ISSUE THREAD

**Issue by aksakalli** [go-graphite/go-carbon#283]
I am using [this docker image](https://github.com/go-graphite/docker-go-graphite) to run `go-carbon`.

[A stress tester](https://github.com/feangulo/graphite-stresser) sends metrics every second to `go-carbon`. I changed the `storage-schemas.conf` for higher rate for `STRESS.` metrics:

```
[stress]
pattern = ^STRESS\.
retentions = 1s:2m,1m:20m

[default]
pattern = .*
retentions = 60s:30d,1h:5y
```

However, I can still only retrieve the points for each minute in Graphana.

**Comment by azhiltsov** [comment]
You need to remove files. 
whisper files probably were created with old metadata and won't be changed until you delete them

**Comment by aksakalli** [comment]
Yes, I already removed the folder and restarted go-carbon before sending the metrics. 

```
docker exec -it go-graphite rm -rf /var/lib/graphite/whisper/STRESS
docker restart go-graphite
```

**Comment by azhiltsov** [comment]
I couldn't reproduce your problem.
My guess that in grafana you are querying more than 2 minutes of data. In this case, according to storage-schema query will be filled from the archive "1", which is 1m:20m.
Reduce the time frame of your query to be below 2 minutes in order to hit the archive "0" (1s:2m)
You can check the whisper archive on disk with whisper-info.py from whisper package
```
$ whisper-info.py /var/lib/carbon/whisper/STRESS/host/ip-0/com/graphite/stresser/ab.wsp 
maxRetention: 1200
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 1720

Archive 0
retention: 120
secondsPerPoint: 1
points: 120
size: 1440
offset: 40

Archive 1
retention: 1200
secondsPerPoint: 60
points: 20
size: 240
offset: 1480
```

**Comment by aksakalli** [comment]
Oh, you are right!

Here I confirmed that the retention policy was set correctly.

```
whisper-info.py /var/lib/graphite/whisper/STRESS/host/ip-0/com/graphite/stresser/a/mean.wsp 
maxRetention: 1200
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 1720

Archive 0
retention: 120
secondsPerPoint: 1
points: 120
size: 1440
offset: 40

Archive 1
retention: 1200
secondsPerPoint: 60
points: 20
size: 240
offset: 1480
```
I changed the query range to `From: now-1m` & `To: now` in Grafana and now I can see all the points. Also, I can retrieve the points from carbonweb as:

```
root@bc25fdf943df:/# curl 'http://localhost:8081/render?target=STRESS.host.ip-0.com.graphite.stresser.a.count&format=json&from=-5s' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0  19869      0 --:--:-- --:--:-- --:--:-- 23142
[
    {
        "datapoints": [
            [
                884,
                1553513937
            ],
            [
                884,
                1553513938
            ],
            [
                884,
                1553513939
            ],
            [
                885,
                1553513940
            ],
            [
                null,
                1553513941
            ]
        ],
        "target": "STRESS.host.ip-0.com.graphite.stresser.a.count"
    }
]
```

Thank you for helping! :relaxed:
