### ISSUE TITLE
tests for points seem overly strict.

### ISSUE THREAD

**Issue by drawks** [go-graphite/go-carbon#3]
Currently there are a bunch of tests in points_test.go that appear to be designed for errors raised on minor problems with the input to ParseText. I notice however that it doesn't appear that ParseText implements the checks which the test expects.

I suppose that it makes sense to write the test first and then implement the expected behavior, however... in this case I think that the additional sanitization of input is unneeded. For instance "foo..bar" splits to fields like ["foo","","bar"] which, when building the path with filepath.join ends up collapsing out the empty path element. Similarly a leading "." ends up causing an empty path element between the storage directory and the whisper file name which similarly is collapsed.

The additional step of sanitization of these metric names would seem to be a wasted effort, even metric names like "foo.bar.." lead to only marginally confusing whisper file names like "foo/bar/.wsp" which arguably are valid and should be allowed.

**Comment by lomik** [comment]
I need this validations for scan bugs in carbon clients (metric senders). You're right - I will make strict mode is optional
