### ISSUE TITLE
find requests to root in carbonserver are too slow

### ISSUE THREAD

**Issue by azhiltsov** [go-graphite/go-carbon#301]
carbonserver find requests like `/metrics/find?query=*el*` are taking too much time to complete.
I case with only ~20 root folders it takes ~1 second to respond.

**Comment by Civil** [comment]
As far as I remember, that's the drawback of trigram index. And as far as I still remember, there were some discussions about finding alternative to that to handle this cases better, however it will worsen other cases and maybe the best option for you would be to add a special case to find logic to handle this type of requests without using trigram index at all.

**Comment by bom-d-van** [comment]
hi @azhiltsov , I think we can resolve this issue now with adoption of trie index, right?

**Comment by azhiltsov** [comment]
I think so. Trie is handling it much faster.
