### ISSUE TITLE
Trigram index on reversed metric paths

### ISSUE THREAD

**Issue by grzkv** [go-graphite/go-carbon#302]
The intersects of a trigram index are faster if more metrics are excluded during the first iterations.  It is common that metric names have more variation in the end rather than in the beginning. Thus, if one would build the trigram index on the reversed metric names, the size of intersects would decrease much faster because more metrics to intersect with would be excluded during the first iterations.

Maybe, we could have an option to use the reversed metric names when indexing.

Please, share your thoughts.

**Comment by dgryski** [comment]
https://github.com/dgryski/go-trigram/blob/master/trigram.go#L214

The commit that added this: https://github.com/dgryski/go-trigram/commit/2546e93d77966f47bb59935e4e7630289ae22af6

**Comment by grzkv** [comment]
@dgryski Thanks for the clarification.
