### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by superopsdev** [go-graphite/go-carbon#306]
when I install the go-carbon ，what means of below messages:
go build --ldflags '-X main.BuildVersion=v0.14.0-21-gdfd2' github.com/lomik/go-carbon
/disk/opt/go-carbon/_vendor/src/github.com/lomik/go-carbon/vendor/github.com/go-graphite/go-whisper/compress.go:9:2: cannot find package "math/bits" in any of:
	/disk/opt/go-carbon/_vendor/src/github.com/lomik/go-carbon/vendor/math/bits (vendor tree)
	/usr/local/go/src/math/bits (from $GOROOT)
	/disk/opt/go-carbon/_vendor/src/math/bits (from $GOPATH)
make: *** [go-carbon] Error 1

**Comment by lomik** [comment]
Upgrade your golang to a more recent version. `math/bits` was introduced in golang 1.9.
