### ISSUE TITLE
why cwhisper format file *.wsp file grow?

### ISSUE THREAD

**Issue by gaoxp** [go-graphite/go-carbon#309]
when i use cwhisper format store metric, i find cwhisper format file *.wsp file will grow, does this will stop or it will grow forever?

**Comment by deniszh** [comment]
@bom-d-van should know

**Comment by azhiltsov** [comment]
It uses the same whisper retention + aggregation ideology, it should stay below uncompressed whisper sizes, right @bom-d-van ?
Cost of datapoint in uncompressed whisper is around 12 bytes, so you can do a calculation for uncompressed whisper and compare:
```
# E.g.: ``1s:3d,60s:14d,1h:2y'':
# - (3600/1)*24*3 +
# - (3600/60)*24*14 +
# - (3600/3600)*24*365.2524*2 
# - multiplied by 12 bytes per point
```
So, answering your question: I would expect it to stop eventually, and if it does not, then might be there a bug?

**Comment by Civil** [comment]
@azhiltsov with all delta/double-delta type of compression, there is always a worst case that will result in more space consumption than the original, uncompressed one. Gorilla is no exception here.

https://github.com/go-graphite/go-whisper/blob/master/compress.go#L595-L629

As per there, the worst case, even though is very unlikely would consume 36 bits for timestamp and 66 bits for value, which will be about 13 bytes per point or so (depends on how to count block headers as well). But author should know better how to calculate that.

**Comment by bom-d-van** [comment]
There is some level of documentations about the growing that I mentioned in [the go-whisper readme](https://github.com/go-graphite/go-whisper#drawbacks) and [the original PR](https://github.com/go-graphite/go-whisper/pull/1). 

@gaoxp the size growing per metrics might happen a few times per metric in the beginning, but its size should stay stable after that if the data points doesn't change its pattern dramatically.

So the growing behind the scene is that cwhisper assumes [a small default size](https://github.com/go-graphite/go-whisper/blob/master/compress.go#L47) per data point as 2, which is big enough if data points are simple (like always 0 or just remain the same value or consistent), but if the data points are complex or random, then 2 bytes is not enough, and cwhipser need to [extend its file size](https://github.com/go-graphite/go-whisper/blob/master/compress.go#L490) (by creating a new file and copying all the data from the old file to new file, and then mv new old).

I will move some documentations from PR to the readme so users could have more knowledge about it.

(I had been trying to avoid this extension/grow design, but it seems to me that this is unavoidable to keep the simplicity and elegance of one metric per file design in Graphite. And it fits better for the current Go-Graphite tooling that we have here.)

**Comment by gaoxp** [comment]
> There is some level of documentations about the growing that I mentioned in [the go-whisper readme](https://github.com/go-graphite/go-whisper#drawbacks) and [the original PR](https://github.com/go-graphite/go-whisper/pull/1).
> 
> @gaoxp the size growing per metrics might happen a few times per metric in the beginning, but its size should stay stable after that if the data points doesn't change its pattern dramatically.
> 
> So the growing behind the scene is that cwhisper assumes [a small default size](https://github.com/go-graphite/go-whisper/blob/master/compress.go#L47) per data point as 2, which is big enough if data points are simple (like always 0 or just remain the same value or consistent), but if the data points are complex or random, then 2 bytes is not enough, and cwhipser need to [extend its file size](https://github.com/go-graphite/go-whisper/blob/master/compress.go#L490) (by creating a new file and copying all the data from the old file to new file, and then mv new old).
> 
> I will move some documentations from PR to the readme so users could have more knowledge about it.
> 
> (I had been trying to avoid this extension/grow design, but it seems to me that this is unavoidable to keep the simplicity and elegance of one metric per file design in Graphite. And it fits better for the current Go-Graphite tooling that we have here.)


if cwhisper extend its file size by creating a new file and copying all the data from the old file to new file, and then mv new old , when cwhisper file have too many data points and need to extend its file size, does it will have a bad performance for read and write?

**Comment by bom-d-van** [comment]
@gaoxp the growing only happen if cwhisper detects that file size isn't big enough for saving the data. It has performance penalty for sure. I didn't measure how big the impact could be because I considered it an event doesn't happen frequently to a specific metric file. There is metrics reported from go-carbon you could use it to see how many metrics are being extended over time: carbon.agents.*.persister.extended

To put things on perspective, on our production instances (each serving a few millions of metrics), I am seeing ~100 metrics being resized every half an hour or so (but your mileage may vary as it depends on your retention and aggregation policy).

**Comment by gaoxp** [comment]
> @gaoxp the growing only happen if cwhisper detects that file size isn't big enough for saving the data. It has performance penalty for sure. I didn't measure how big the impact could be because I considered it an event doesn't happen frequently to a specific metric file. There is metrics reported from go-carbon you could use it to see how many metrics are being extended over time: carbon.agents.*.persister.extended
> 
> To put things on perspective, on our production instances (each serving a few millions of metrics), I am seeing ~100 metrics being resized every half an hour or so (but your mileage may vary as it depends on your retention and aggregation policy).

ok,I will close this issue,thank you
