### ISSUE TITLE
Fetching Prometheus endpoint returns 404

### ISSUE THREAD

**Issue by obfuscurity** [go-graphite/go-carbon#311]
Apologies if I'm overlooking something stupid... the Prometheus metrics endpoint seems to be supported in 0.14.0 but I'm unable to get it working correctly. I'm running with a basic setup but I hit a 404 error any time I try to curl the endpoint.

Relevant config bits:
```
[carbonserver]
listen = "127.0.0.1:8080"
enabled = true

[prometheus]
endpoint = "/metrics"
enabled = true
```
Query attempt:
```
$ curl -vv http://localhost:8080/metrics
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Vary: Accept-Encoding
< X-Content-Type-Options: nosniff
< Date: Thu, 26 Sep 2019 18:47:34 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host localhost left intact
```

**Comment by azhiltsov** [comment]
@obfuscurity If I am not mistaken they are exposed on pprof port.
Additionally to that there were many changes related to this recently, which are not in release yet. We are running from master in production, should be safe to try.

**Comment by obfuscurity** [comment]
@azhiltsov I can confirm this works after enabling and querying the pprof port. Thank you!
