### ISSUE TITLE
go-carbon Disk high read requests

### ISSUE THREAD

**Issue by mzaian** [go-graphite/go-carbon#312]
We have a go-carbon setup of with version 0.13.0 and We can see that we have a very high disk read caused by go-carbon. I have seen another issue here https://github.com/lomik/go-carbon/issues/297 but the difference is we do not use carbonserver, we do have carbonlink enabled.

We have the recommendations from here https://github.com/lomik/go-carbon/#os-tuning in place. 

Here are some answers to the questions from this issue:

How many whisper files on the disk are getting updates within 5 minutes
414474 files

What filesystem do you use for whispers?
ext4

~# cat /proc/slabinfo
slabinfo - version: 2.1
name            <active_objs> <num_objs> <objsize> <objperslab> <pagesperslab> : tunables <limit> <batchcount> <sharedfactor> : slabdata <active_slabs> <num_slabs> <sharedavail>
nfs4_layout_stateid      0      0    296   55    4 : tunables    0    0    0 : slabdata      0      0      0
nfsd4_stateids       368    368    176   46    2 : tunables    0    0    0 : slabdata      8      8      0
nfsd4_files         1008   1008    288   56    4 : tunables    0    0    0 : slabdata     18     18      0
nfsd4_openowners     111    111    440   37    4 : tunables    0    0    0 : slabdata      3      3      0
nfs_direct_cache       0      0    352   46    4 : tunables    0    0    0 : slabdata      0      0      0
nfs_inode_cache      308    308   1016   32    8 : tunables    0    0    0 : slabdata     35     35      0
fscache_cookie_jar    368    368     88   46    1 : tunables    0    0    0 : slabdata      8      8      0
rpc_inode_cache      408    408    640   51    8 : tunables    0    0    0 : slabdata      8      8      0
ext4_groupinfo_4k  21728  21728    144   56    2 : tunables    0    0    0 : slabdata    388    388      0
UDPLITEv6              0      0   1088   30    8 : tunables    0    0    0 : slabdata      0      0      0
UDPv6                240    240   1088   30    8 : tunables    0    0    0 : slabdata      8      8      0
tw_sock_TCPv6         58     58    280   58    4 : tunables    0    0    0 : slabdata      1      1      0
request_sock_TCPv6      0      0    328   49    4 : tunables    0    0    0 : slabdata      0      0      0
TCPv6                180    180   2112   15    8 : tunables    0    0    0 : slabdata     12     12      0
kcopyd_job             0      0   3312    9    8 : tunables    0    0    0 : slabdata      0      0      0
dm_uevent              0      0   2632   12    8 : tunables    0    0    0 : slabdata      0      0      0
cfq_queue              0      0    232   70    4 : tunables    0    0    0 : slabdata      0      0      0
bsg_cmd                0      0    312   52    4 : tunables    0    0    0 : slabdata      0      0      0
mqueue_inode_cache     36     36    896   36    8 : tunables    0    0    0 : slabdata      1      1      0
fuse_request         160    160    400   40    4 : tunables    0    0    0 : slabdata      4      4      0
fuse_inode            20     20    768   42    8 : tunables    0    0    0 : slabdata      4      4      0
ecryptfs_key_record_cache      0      0    576   56    8 : tunables    0    0    0 : slabdata      0      0      0
ecryptfs_sb_cache      0      0   1152   28    8 : tunables    0    0    0 : slabdata      0      0      0
ecryptfs_inode_cache      0      0   1024   32    8 : tunables    0    0    0 : slabdata      0      0      0
ecryptfs_auth_tok_list_item      0      0    832   39    8 : tunables    0    0    0 : slabdata      0      0      0
fat_inode_cache        0      0    704   46    8 : tunables    0    0    0 : slabdata      0      0      0
fat_cache              0      0     40  102    1 : tunables    0    0    0 : slabdata      0      0      0
hugetlbfs_inode_cache    112    112    584   56    8 : tunables    0    0    0 : slabdata      2      2      0
squashfs_inode_cache      0      0    640   51    8 : tunables    0    0    0 : slabdata      0      0      0
jbd2_journal_handle    680    680     48   85    1 : tunables    0    0    0 : slabdata      8      8      0
jbd2_journal_head  19243  24820    120   68    2 : tunables    0    0    0 : slabdata    365    365      0
jbd2_revoke_table_s    512    512     16  256    1 : tunables    0    0    0 : slabdata      2      2      0
jbd2_revoke_record_s   7808   7808     32  128    1 : tunables    0    0    0 : slabdata     61     61      0
ext4_inode_cache  2854098 2854098   1072   30    8 : tunables    0    0    0 : slabdata 338727 338727      0
ext4_free_data      3968   3968     64   64    1 : tunables    0    0    0 : slabdata     62     62      0
ext4_allocation_context    512    512    128   64    2 : tunables    0    0    0 : slabdata      8      8      0
ext4_io_end         3752   3976     72   56    1 : tunables    0    0    0 : slabdata     71     71      0
ext4_extent_status 3603384 4203420     40  102    1 : tunables    0    0    0 : slabdata  41210  41210      0
dquot                512    512    256   64    4 : tunables    0    0    0 : slabdata      8      8      0
userfaultfd_ctx_cache      0      0    128   64    2 : tunables    0    0    0 : slabdata      0      0      0
dio                    0      0    640   51    8 : tunables    0    0    0 : slabdata      0      0      0
pid_namespace          0      0   2224   14    8 : tunables    0    0    0 : slabdata      0      0      0
posix_timers_cache    884    884    240   68    4 : tunables    0    0    0 : slabdata     13     13      0
ip4-frags              0      0    216   37    2 : tunables    0    0    0 : slabdata      0      0      0
UDP-Lite               0      0    960   34    8 : tunables    0    0    0 : slabdata      0      0      0
flow_cache             0      0    112   36    1 : tunables    0    0    0 : slabdata      0      0      0
xfrm_dst_cache         0      0    448   36    4 : tunables    0    0    0 : slabdata      0      0      0
RAW                  568    592    896   36    8 : tunables    0    0    0 : slabdata     68     68      0
UDP                  272    272    960   34    8 : tunables    0    0    0 : slabdata      8      8      0
tw_sock_TCP         6438   6438    280   58    4 : tunables    0    0    0 : slabdata    111    111      0
request_sock_TCP     392    392    328   49    4 : tunables    0    0    0 : slabdata      8      8      0
TCP                  280    303   1920   17    8 : tunables    0    0    0 : slabdata     39     39      0
blkdev_queue          72     72   1336   24    8 : tunables    0    0    0 : slabdata      3      3      0
blkdev_requests     2981   2981    368   44    4 : tunables    0    0    0 : slabdata     82     82      0
blkdev_ioc           585    585    104   39    1 : tunables    0    0    0 : slabdata     15     15      0
user_namespace         0      0    304   53    4 : tunables    0    0    0 : slabdata      0      0      0
dmaengine-unmap-256     15     15   2112   15    8 : tunables    0    0    0 : slabdata      1      1      0
sock_inode_cache    1484   1971    640   51    8 : tunables    0    0    0 : slabdata     66     66      0
file_lock_cache      819    819    208   39    2 : tunables    0    0    0 : slabdata     21     21      0
net_namespace         40     40   6272    5    8 : tunables    0    0    0 : slabdata      8      8      0
shmem_inode_cache   4664   4900    656   49    8 : tunables    0    0    0 : slabdata    100    100      0
taskstats            392    392    328   49    4 : tunables    0    0    0 : slabdata      8      8      0
proc_inode_cache    4475   4920    624   52    8 : tunables    0    0    0 : slabdata    176    176      0
sigqueue             408    408    160   51    2 : tunables    0    0    0 : slabdata      8      8      0
bdev_cache           312    312    832   39    8 : tunables    0    0    0 : slabdata      8      8      0
kernfs_node_cache  63784  63784    120   68    2 : tunables    0    0    0 : slabdata    939    939      0
mnt_cache           2656   2656    384   42    4 : tunables    0    0    0 : slabdata     64     64      0
inode_cache        12720  12996    568   57    8 : tunables    0    0    0 : slabdata    278    278      0
dentry            2146411 2884245    192   42    2 : tunables    0    0    0 : slabdata  72918  72918      0
iint_cache             0      0     72   56    1 : tunables    0    0    0 : slabdata      0      0      0
buffer_head       5360178 6041178    104   39    1 : tunables    0    0    0 : slabdata 154902 154902      0
vm_area_struct     20944  21560    200   40    2 : tunables    0    0    0 : slabdata    539    539      0
files_cache          506    506    704   46    8 : tunables    0    0    0 : slabdata     11     11      0
signal_cache        1057   1182   1088   30    8 : tunables    0    0    0 : slabdata     43     43      0
sighand_cache        587    639   2112   15    8 : tunables    0    0    0 : slabdata     51     51      0
task_struct          630    684   3584    9    8 : tunables    0    0    0 : slabdata     76     76      0
Acpi-Operand       11480  11480     72   56    1 : tunables    0    0    0 : slabdata    205    205      0
Acpi-Parse          1168   1168     56   73    1 : tunables    0    0    0 : slabdata     16     16      0
Acpi-State           561    561     80   51    1 : tunables    0    0    0 : slabdata     11     11      0
Acpi-Namespace     10098  10098     40  102    1 : tunables    0    0    0 : slabdata     99     99      0
anon_vma            9820  10965     80   51    1 : tunables    0    0    0 : slabdata    215    215      0
numa_policy          170    170     24  170    1 : tunables    0    0    0 : slabdata      1      1      0
radix_tree_node   8086372 8623524    584   56    8 : tunables    0    0    0 : slabdata 213754 213754      0
trace_event_file    1794   1794     88   46    1 : tunables    0    0    0 : slabdata     39     39      0
ftrace_event_field 2240924 2245955     48   85    1 : tunables    0    0    0 : slabdata  26423  26423      0
idr_layer_cache      622    622   2096   15    8 : tunables    0    0    0 : slabdata     48     48      0
dma-kmalloc-8192       0      0   8192    4    8 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-4096       0      0   4096    8    8 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-2048       0      0   2048   16    8 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-1024       0      0   1024   32    8 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-512        0      0    512   64    8 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-256        0      0    256   64    4 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-128        0      0    128   64    2 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-64         0      0     64   64    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-32         0      0     32  128    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-16         0      0     16  256    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-8          0      0      8  512    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-192        0      0    192   42    2 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-96         0      0     96   42    1 : tunables    0    0    0 : slabdata      0      0      0
kmalloc-8192         354    363   8192    4    8 : tunables    0    0    0 : slabdata    105    105      0
kmalloc-4096         289    318   4096    8    8 : tunables    0    0    0 : slabdata     66     66      0
kmalloc-2048        1643   1700   2048   16    8 : tunables    0    0    0 : slabdata    115    115      0
kmalloc-1024        2540   2816   1024   32    8 : tunables    0    0    0 : slabdata     88     88      0
kmalloc-512        11320  11320    512   64    8 : tunables    0    0    0 : slabdata    253    253      0
kmalloc-256         7697  12160    256   64    4 : tunables    0    0    0 : slabdata    196    196      0
kmalloc-192        11229  16527    192   42    2 : tunables    0    0    0 : slabdata    396    396      0
kmalloc-128        13760  13760    128   64    2 : tunables    0    0    0 : slabdata    215    215      0
kmalloc-96         42487  53004     96   42    1 : tunables    0    0    0 : slabdata   1262   1262      0
kmalloc-64         82629 101120     64   64    1 : tunables    0    0    0 : slabdata   1580   1580      0
kmalloc-32         15793  18944     32  128    1 : tunables    0    0    0 : slabdata    148    148      0
kmalloc-16         35840  35840     16  256    1 : tunables    0    0    0 : slabdata    140    140      0
kmalloc-8          69120  69120      8  512    1 : tunables    0    0    0 : slabdata    135    135      0
kmem_cache_node      512    512     64   64    1 : tunables    0    0    0 : slabdata      8      8      0
kmem_cache           512    512    256   64    4 : tunables    0    0    0 : slabdata      8      8      0

~#  cat /proc/meminfo
MemTotal:       66483996 kB
MemFree:         2658496 kB
MemAvailable:   61170668 kB
Buffers:         2398304 kB
Cached:         46966388 kB
SwapCached:        46764 kB
Active:         28656392 kB
Inactive:       24758984 kB
Active(anon):    3313760 kB
Inactive(anon):   737360 kB
Active(file):   25342632 kB
Inactive(file): 24021624 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      16777212 kB
SwapFree:       16306524 kB
Dirty:            705576 kB
Writeback:             0 kB
AnonPages:       4036516 kB
Mapped:            48124 kB
Shmem:               568 kB
Slab:            9716468 kB
SReclaimable:    9541904 kB
SUnreclaim:       174564 kB
KernelStack:        8736 kB
PageTables:        26424 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    50019208 kB
Committed_AS:    7114876 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:    163840 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:     1986368 kB
DirectMap2M:    41005056 kB
DirectMap1G:    26214400 kB

~#  ps -C go-carbon -o vsz,rss,%mem,cmd
   VSZ   RSS %MEM CMD
5285312 3692220  5.5 /usr/bin/go-carbon -config /etc/go-carbon/go-carbon.conf -pidfile /var/run/go-carbon.pid -daemon

~# grep retentions /etc/go-carbon/storage-schemas.conf
retentions = 10s:6h,1m:30d,15m:1y
retentions = 1m:180d
retentions = 15m:1y
retentions = 1d:5y
retentions = 1d:5y
retentions = 10s:7d,1m:90d,15m:1y
retentions = 5m:30d,15m:90d,1h:1y,3h:3y
retentions = 1m:30d,15m:1y

**Comment by deniszh** [comment]
Hi @mzaian,
Please note that high number of disk operations can be quite normal for go-carbon. Ho much metrics per minute have this instance?
It's totally possible that you just overgrow io ability of single server and you need to scale it horizontally or vertically.

**Comment by mzaian** [comment]
Hi @deniszh,

We have a quite big number of metrics but we have another node which is hardware with Flash storage on PCIe and It not doing the same high amount of reads.

Here is a sample of what I see from iostat:

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00   654.40 6145.40    5.60 38505.60  2640.00    13.38     3.53    0.57    0.56   13.00   0.16  99.92

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00   628.20 6191.80    5.40 38813.60  2534.40    13.34     3.52    0.57    0.56   12.30   0.16  99.92

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00   630.00 6628.80    5.40 41444.00  2541.60    13.26     3.50    0.53    0.52   12.89   0.15  99.76

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00   694.80 6720.80    6.00 42151.20  2803.20    13.37     3.48    0.52    0.51   13.20   0.15  99.92

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00   706.60 6617.40    6.00 41565.60  2850.40    13.41     3.46    0.52    0.51   12.00   0.15  99.68

So the utilization is nearly 100% percent.

**Comment by azhiltsov** [comment]
the ext4_inode_cache active_obj is 2854098 but you saying that only ~400K files are updated every 5min
What is the output of df -i for the filesystem with whispers? 
and how many whispers on the disk in total

The read load could be produced by:
- render queries
do you have amount of datapoints you serve for read from this host? Can you disable rendering from  it to confirm that it not caused by it?

- bug in the code, like https://github.com/lomik/go-carbon/pull/299
you can build and run from the master (we are running it in production for a while now, so should be safe)

- write read amplification  
ie: metric with retentions = 5m:30d,15m:90d,1h:1y,3h:3y
will need to be read 3 times on every update. In case if your machine does not have enough RAM to hold page caches in its memory then pages can be evicted by the time they actually needed. With update frequency 1 point every 5min (using this as example for given retention) chances are quite high. 

- misconfiguration in go-carbon 
would you mind to share your config?

**Comment by mzaian** [comment]
Hello,

- This is the amount of inodes on this disk
Filesystem        Inodes   IUsed     IFree IUse% Mounted on
/dev/sdc1      176947200 2852529 174094671    2% /virtual

- How many whispers on disk
2357787

- go-carbon conf

[common]
user = "www-data"
graph-prefix = "carbon.agents.{host}."
max-cpu = 8
metric-interval = "1m0s"

[[logging]]
#logger = ""
#log-level = "info"
log-level = "error"
logfile = "/PATH/go-carbon.log"
#file = "stderr"
#level = "error"

[whisper]
data-dir = "/PATH/graphite/storage/whisper/"
schemas-file = "/etc/go-carbon/storage-schemas.conf"
aggregation-file = "/etc/go-carbon/storage-aggregation.conf"
workers = 4
max-updates-per-second = 10000
sparse-create = false
enabled = true

[cache]
max-size = 51200000
input-buffer = 51200000
write-strategy = "noop"
#write-strategy = "max"

[udp]
listen = ":2005"
enabled = true
log-incomplete = false

[tcp]
listen = ":2005"
enabled = true
buffer-size = 5120000

[pickle]
listen = ":2004"
max-message-size = 67108864
enabled = true

[carbonlink]
listen = "127.0.0.1:7002"
enabled = true
read-timeout = "15s"
query-timeout = "200ms"

[pprof]
listen = "localhost:7007"
enabled = false

I will check the rest of your questions but maybe we find something here.

**Comment by mzaian** [comment]
I've checked now all the mentioned points in https://github.com/lomik/go-carbon/issues/312#issuecomment-537468663 and one thing now I want to know how can I improve for example for these specific retentions. We are using this storage schema for collecting network stuff I.E librenms.
- write read amplification
ie: metric with retentions = 5m:30d,15m:90d,1h:1y,3h:3y

**Comment by bom-d-van** [comment]
@mzaian if you are using trigram-index, it also falls back to filesystem globbing for some type of queries (like full-path queries, without *, {}, [], ? etc). 

In our recent test of [trie-index](https://github.com/lomik/go-carbon/pull/303), we have observed significant read io drops (on some servers from 73k to 1.4k). If you are brave, maybe you would like try the new index out? ;) 

It haven't been merged yet, but it is good enough to test it on production. I'm curious if it would help your usage.

Note: for certain types of queries, trie index performs worse than trigram though, for example, queries contains many stars like system.*server-name*.cpu.idle, and it also depends on your production workload. The good part is, we also observe good testing result for many of our clusters.

**Comment by mzaian** [comment]
@bom-d-van I'm happy to try this out in one of the machines we use to test and it has the same data as the production nodes. But I want to clarify some information. So change will do nothing to the files or structure. So all these changes are running in memory and does change the data.

Update:
I just noticed that either trigram-index or trie-index are options for [carbonserver] and we are not using it.

**Comment by bom-d-van** [comment]
Lovely, and yes, it's all in-memory and has not persistent changes.

And trigram-index is enabled by default so you should be using it already. You just need to set trie-index to be true for enabling the new index.

**Comment by mzaian** [comment]
> Lovely, and yes, it's all in-memory and has not persistent changes.
> 
> And trigram-index is enabled by default so you should be using it already. You just need to set trie-index to be true for enabling the new index.

But as I wrote this is only for [carbonserver] right? and We are not using it. We are using [carbonlink]

**Comment by bom-d-van** [comment]
> But as I wrote this is only for [carbonserver] right? and We are not using it. We are using [carbonlink]

Oh, I missed that. Yeah, I don't have much knowledge about carbonlink actually. But by a quick skimming through the code, yeah, I don't think the new index would help you. 

Sorry for the confusion. :P

**Comment by azhiltsov** [comment]
carbonserver which we are using has it internal query cache (this could be one of the reasons why we have very small amount of read io). I do not know how carbonlink is dealing with reads, does it have any caching layer etc, but this is something to check. 
Another factor to reduce the Read IO is OS page cache (which seems to be fine in your case) but you need to take in account how deep to the history your queries are actually looking. Might be there is not enough RAM to keep pages around. (Did you try to disable carbonlink, but keep metrics flow? Was there any change in amount of read IO?)
Another thing what concerns me is whisper files to inode ratio:
in our case we have lets say 1KK whispers per 3KK inodes (many folders, many files)
in your case it 2.2KK per 2.8KK I can guess there a some folders with a lot of files in them. This structure might require more time when you querying it, https://serverfault.com/a/796696 especially if there is globing (*) query falling on that big folder 
We are using XFS and 4.19 kernel by the way - so can't do direct comparison.
Last think is read amplification - you can't fight with it, only one think comes to my mind is RAM. 

So recommendation will be: 
Disable render queries to check where is the source or reads.
Give it more RAM to hold more page cache.
Try XFS + kernel above 4.15
change metrics structure (more folders, if I guessed right)
