### ISSUE TITLE
Many strange creates when flushing/USR2

### ISSUE THREAD

**Issue by szibis** [go-graphite/go-carbon#33]
We have big traffic in graphite creates are very delayed on go-carbon with such traffic.

When we stop or USR2 on go-carbon then, a huge number of creates flushing on drives. I think it is related to https://github.com/lomik/go-carbon/issues/32

Most of this creates are empty or have 2-10 data updates and then nothing - null values

Is there any setting i miss ?

**Comment by lomik** [comment]
I don't understand anything. Describe the problem more detail please

**Comment by szibis** [comment]
Ok i will try explain, but after some changes in https://github.com/lomik/go-carbon/issues/32 problem is gone/minimised. 

Before, when i hit throttling problems I was not able to control updates. 
What was strange is that when go-carbon works for some time i have some signals from people that creates they made appears after hours. Just after go-carbon restart buffers flushing and many creates made/appears.
All this creates gets, a lot of storage and some of them are almost empty with one or few updates only and they where never updated anymore on this node. 
All this seems like throttling effect ? Maybe empty metrics is not go-carbon problem and i will look for more explanation in my flow, but effect of very long create times now almost disappear when updates are faster committed to drives and cache is short.

**Comment by drawks** [comment]
Between dump/restore on shutdown (#61), configurable write strategies (#60, #79, #81) and fair queuing (#84) I think this issue is resolved as it will ever be. Users are empowered to tune their cache/write behavior to suit their storage back-end AND have a decent method for handling restarts without being bottle necked on a full cache flush if their storage is having trouble keeping up.

@lomik?

**Comment by lomik** [comment]
Everything has changed (and USR2 behavior too), it is unlikely the problem is urgent
