### ISSUE TITLE
Quick question re metrics in cache vs metrics on disk

### ISSUE THREAD

**Issue by mhollick** [go-graphite/go-carbon#34]
Hi,

Does the storage schema affect the resolution of the metrics stored in the cache?

ie if the storage schema is '10s:100d' and I feed go-carbon metrics at a 1 second interval will a query to the cache result in metrics at 1 or 10 second resolution?

cheers.

**Comment by lomik** [comment]
Storage schema doesn't affect cache. In your example cache resolution is one point per one second.
