### ISSUE TITLE
Switch to go modules?

### ISSUE THREAD

**Issue by avereha** [go-graphite/go-carbon#346]
It seems that `dep` is used less and less:
"dep was initially developed to experiment with a new dependency management system for Go; but, as of Go 1.11, the Go project has officially adopted a different approach, based on the concept of Modules, which is described in a series of posts published on blog.golang.org."

**Comment by avereha** [comment]
The main reason I was asking this question is that I'm thinking to also add tracing support(https://github.com/open-telemetry/opentelemetry-go) and those libraries are published only as go modules. 

Is there any concern if I will contribute those two changes?

**Comment by deniszh** [comment]
I think that's a good idea, but let's review and merge other PRs first

**Comment by avereha** [comment]
Started working on this here: https://github.com/go-graphite/go-carbon/commits/avereha/gomod
Can open PR later/when we have less pending PRs.

**Comment by deniszh** [comment]
I finished with merging/sorting PRs and want to make release soon, preparing documentation and pipeline now. You can create PR if want / ready, @avereha !

**Comment by avereha** [comment]
Thank you! I just opened PR.

**Comment by deniszh** [comment]
Merged now, thanks!
