### ISSUE TITLE
Problem with installing go-carbon_0.15.0_amd64.deb

### ISSUE THREAD

**Issue by u10t010** [go-graphite/go-carbon#362]
Hello, 
following problem occurs when trying to install go-carbon_0.15.0_amd64.deb
It look likes bzip2 has been used instead of gzip

_root@xxxxxxxx:~# dpkg -i /opt/go-carbon_0.15.0_amd64.deb 
tar: Archive is compressed. Use -j option
tar: Error is not recoverable: exiting now
dpkg-deb: error: tar subprocess returned error exit status 2
dpkg: error processing archive /opt/go-carbon_0.15.0_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /opt/go-carbon_0.15.0_amd64.deb_

Could you please be so kind and look for this.
Thank you in advance.
best regards,
u10t010

**Comment by deniszh** [comment]
Hello @u10t010,

Yes, bzip2 compression was used when building deb package, as we always do, with `fpm... --deb-compression bzip2`.
What's wrong with it? Which system are you using as it doesn't support that?

**Comment by deniszh** [comment]
Ah, probably it's because of https://github.com/jordansissel/fpm/pull/1611
fpm should be pinned to 1.10.2 already

**Comment by deniszh** [comment]
I rebuilt and reupload packages, should be fixed now. That happened because of broken pipeline, next release it should be fixed already.
