### ISSUE TITLE
Apply common go linters

### ISSUE THREAD

**Issue by deniszh** [go-graphite/go-carbon#365]
It's good to have `go fmt`, `go mod tidy` etc. to be applied / tested on every PR.

**Comment by dgryski** [comment]
Also `go vet`.  I recommend also `ineffassign`, `nilness` and of course `staticcheck`, but getting all these passing will require some code changes.

(While we're listing linters I like: ruleguard and gocritic are also reasonable).

**Comment by deniszh** [comment]
Yes, enabling linters is easy, but for changes I need a bit of time. :P

**Comment by deniszh** [comment]
And (as I lazy) I'm mostly looking for applying tuned [golangci](https://golangci-lint.run/usage/linters/) through [golangci-lint-action](https://github.com/golangci/golangci-lint-action).

**Comment by deniszh** [comment]
Implemented in https://github.com/go-graphite/go-carbon/pull/368
