### ISSUE TITLE
[BUG] find failed, can't expand globs

### ISSUE THREAD

**Issue by obfuscurity** [go-graphite/go-carbon#379]
**Describe the bug**
We attempted to upgrade from go-carbon 0.14.0 to version 0.15.0. Initially the upgrade seemed to go fine, but shortly afterwards we began seeing no data in Grafana and traced the issue back to these errors in the go-carbon logs.

**Logs**
The following log has been sanitized for the _hostname_ and _metric_ strings. The metric string contained dot-delimited alphanumeric characters but no wildcard characters.

Oct 20 15:49:35 hostname go-carbon[130923]: {"level":"ERROR","timestamp":"2020-10-20T15:49:35.633Z","logger":"access","message":"fetch failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:33600","carbonapi_uuid":"54ff70c2-a91b-47d4-82e0-e95e4a1685c0","carbonzipper_uuid":"54ff70c2-a91b-47d4-82e0-e95e4a1685c0","format":"carbonapi_v3_pb","targets":["foo.bar.baz"],"runtime_seconds":0.000319742,"reason":"failed to read data","http_code":400,"error":"find failed, can't expand globs"}

**Go-carbon Configuration:**
```
[common]
user = "carbon"
graph-prefix = "carbon.agents.{host}"
metric-endpoint = "local"
max-cpu = 16
metric-interval = "1m0s"

[whisper]
data-dir = "/data/graphite/whisper"
schemas-file = "/etc/go-carbon/storage-schemas.conf"
#aggregation-file = "/etc/go-carbon/storage-aggregation.conf"
workers = 32
max-updates-per-second = 70000
max-creates-per-second = 2000
hard-max-creates-per-second = false
sparse-create = false
flock = false
hash-filenames = false
enabled = true

[cache]
max-size = 80000000
write-strategy = "max"

[udp]
listen = "127.0.0.1:2003"
log-incomplete = true
buffer-size = 0
enabled = true

[tcp]
listen = "127.0.0.1:2003"
buffer-size = 0
#compression = ""
enabled = true

[pickle]
listen = "127.0.0.1:2004"
max-message-size = 67108864
buffer-size = 0
enabled = true

[carbonlink]
listen = "127.0.0.1:7002"
read-timeout = "30s"
enabled = true

[grpc]
listen = "127.0.0.1:7003"
enabled = true

[tags]
tagdb-url = "http://127.0.0.1:8000"
tagdb-chunk-size = 32
tagdb-update-interval = 100
local-dir = "/var/lib/graphite/tagging/"
tagdb-timeout = "1s"
enabled = false

[carbonserver]
listen = "127.0.0.1:8080"
query-cache-enabled = true
query-cache-size-mb = 0
find-cache-enabled = true
buckets = 10
max-globs = 100
fail-on-max-globs = false
metrics-as-counters = false
trigram-index = false
trie-index = true
internal-stats-dir = ""
read-timeout = "1m0s"
idle-timeout = "1m0s"
write-timeout = "1m0s"
scan-frequency = "5m0s"
enabled = true

[dump]
path = "/var/lib/graphite/dump/"
restore-per-second = 0
enabled = false

[pprof]
listen = "127.0.0.1:7007"
enabled = true

[prometheus]
endpoint = "/metrics"
enabled = true

[prometheus.labels]

[[logging]]
logger = ""
file = "stderr"
level = "warn"
encoding = "json"
encoding-time = "iso8601"
encoding-duration = "seconds"
```

**Metric retention and aggregation schemas**
storage-schemas.conf:
```
[01.carbon]
pattern = ^carbon\.
retentions = 60s:15d,5m:180d

[02.foo]
pattern = ^foo\.bar\.
retentions = 60s:15d,5m:180d

[03.metric_testing]
pattern = ^metric_testing
retentions = 60s:1d,5m:7d

[04.grafana]
pattern = ^grafana\.
retentions = 60s:15d

[99.default_1min_for_90day]
pattern = .*
retentions = 60s:15d,5m:180d
```

**Simplified query (if applicable)**
See logging output.

**Additional context**
This is go-carbon version 0.15.0 running on Ubuntu 16.04.7 LTS. It is being used as a backendsv2 backend (protocol carbonapi_v3_pb) for carbonapi version 0.14.1-1.

**Comment by bom-d-van** [comment]
Hi @obfuscurity can you post more of the error logs? Like `grep 'find failed' go-carbon.log` or `grep ERROR go-carbon.log`. We need a bit more information.

**Comment by obfuscurity** [comment]
Sure, here you go. Hope this helps.

```
Oct 20 15:43:18 hostname go-carbon[167931]: {"level":"ERROR","timestamp":"2020-10-20T15:43:18.293Z","logger":"access","message":"find failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:38116","targets":["foo.bar.requests"],"format":"carbonapi_v3_pb","carbonapi_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","carbonzipper_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","function":"fetchWithCache","runtime_seconds":0.000601148,"reason":"can't expand globs","errors":[{}]}
Oct 20 15:43:18 hostname go-carbon[167931]: {"level":"ERROR","timestamp":"2020-10-20T15:43:18.293Z","logger":"access","message":"fetch failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:38116","carbonapi_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","carbonzipper_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","format":"carbonapi_v3_pb","targets":["foo.bar.requests"],"runtime_seconds":0.000874599,"reason":"failed to read data","http_code":400,"error":"find failed, can't expand globs"}
Oct 20 15:43:18 hostname go-carbon[167931]: {"level":"ERROR","timestamp":"2020-10-20T15:43:18.294Z","logger":"access","message":"find failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:38116","targets":["foo.bar.resp_*"],"format":"carbonapi_v3_pb","carbonapi_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","carbonzipper_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","function":"fetchWithCache","runtime_seconds":0.000180545,"reason":"can't expand globs","errors":[{}]}
Oct 20 15:43:18 hostname go-carbon[167931]: {"level":"ERROR","timestamp":"2020-10-20T15:43:18.294Z","logger":"access","message":"fetch failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:38116","carbonapi_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","carbonzipper_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","format":"carbonapi_v3_pb","targets":["foo.bar.resp_*"],"runtime_seconds":0.000254719,"reason":"failed to read data","http_code":400,"error":"find failed, can't expand globs"}
Oct 20 15:43:18 hostname go-carbon[167931]: {"level":"ERROR","timestamp":"2020-10-20T15:43:18.295Z","logger":"access","message":"find failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:38116","targets":["foo.bar.status_5xx"],"format":"carbonapi_v3_pb","carbonzipper_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","carbonapi_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","function":"fetchWithCache","runtime_seconds":0.000229171,"reason":"can't expand globs","errors":[{}]}
Oct 20 15:43:18 hostname go-carbon[167931]: {"level":"ERROR","timestamp":"2020-10-20T15:43:18.295Z","logger":"access","message":"fetch failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:38116","carbonzipper_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","carbonapi_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","format":"carbonapi_v3_pb","targets":["foo.bar.status_5xx"],"runtime_seconds":0.000316678,"reason":"failed to read data","http_code":400,"error":"find failed, can't expand globs"}
Oct 20 15:43:18 hostname go-carbon[167931]: {"level":"ERROR","timestamp":"2020-10-20T15:43:18.295Z","logger":"access","message":"find failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:38116","targets":["foo.bar.status_4xx"],"format":"carbonapi_v3_pb","carbonapi_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","carbonzipper_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","function":"fetchWithCache","runtime_seconds":0.000341245,"reason":"can't expand globs","errors":[{}]}
Oct 20 15:43:18 hostname go-carbon[167931]: {"level":"ERROR","timestamp":"2020-10-20T15:43:18.295Z","logger":"access","message":"fetch failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:38116","carbonapi_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","carbonzipper_uuid":"56fce0bf-8473-4df7-9fde-735638bef65d","format":"carbonapi_v3_pb","targets":["foo.bar.status_4xx"],"runtime_seconds":0.000507228,"reason":"failed to read data","http_code":400,"error":"find failed, can't expand globs"}
```

**Comment by bom-d-van** [comment]
> errors":[{}]

Oops, it's kinda sad. The errors content are still missed. 
@obfuscurity  Would you be able to test it if I send you a patch to expose the errors? I don't know what's the actual problem here.

There is a chance that it's related to `trie-index`. Have you tried switching back to `trigram-index`?

**Comment by bom-d-van** [comment]
@obfuscurity this patch should help us find out the actual cause: https://github.com/go-graphite/go-carbon/pull/380

**Comment by deniszh** [comment]
@obfuscurity @bom-d-van : I screwed 2 releases but finally released 0.15.3 with latest fixes, including #380 :)

**Comment by obfuscurity** [comment]
We'll give 0.15.3 some isolated testing. Note that we switched to trie index back in June to address some OOM conditions on our systems; this seemed to help a lot so we're hesitant to switch away from it again.

**Comment by bom-d-van** [comment]
@deniszh haha, third time is a charm. thank you for making the release!

@obfuscurity got it, yes, trie is a form of compression itself. If you have memory constraint, you might want to try out enabling `concurrent-index` as well (just released by Denis in v0.15.3), it should have even better memory performance because it only maintains one copy of in-memory index at all time.

**Comment by obfuscurity** [comment]
Ok, here you go. We have not made any configuration changes yet, just deployed v0.15.3 on an isolated host. I can grab more log examples if there's anything in particular you'd like to see.

```
Oct 20 20:59:28 hostname go-carbon[209316]: {"level":"ERROR","timestamp":"2020-10-20T20:59:28.588Z","logger":"access","message":"fetch failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:57648","carbonapi_uuid":"975b2d17-9969-4cab-99bb-c3f45716f80d","carbonzipper_uuid":"975b2d17-9969-4cab-99bb-c3f45716f80d","format":"carbonapi_v3_pb","targets":["foo.bar.requests"],"runtime_seconds":0.000265471,"reason":"failed to read data","http_code":400,"error":"find failed, can't expand globs"}
Oct 20 20:59:28 hostname go-carbon[209316]: {"level":"ERROR","timestamp":"2020-10-20T20:59:28.588Z","logger":"access","message":"find failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:57648","targets":["foo.bar.requests"],"format":"carbonapi_v3_pb","carbonapi_uuid":"975b2d17-9969-4cab-99bb-c3f45716f80d","carbonzipper_uuid":"975b2d17-9969-4cab-99bb-c3f45716f80d","function":"fetchWithCache","runtime_seconds":0.000129634,"reason":"can't expand globs","errors":[{"error":"foo.bar.requests: runtime error: index out of range [208] with length 131\ngoroutine 13732 [running]:\nruntime/debug.Stack(0xc0c76035a0, 0xe88200, 0xc1f5ed1920)\n\t/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/go-graphite/go-carbon/carbonserver.(*CarbonserverListener).expandGlobs.func1(0xc2f63b9c20, 0xc0c7603fc8)\n\t/home/travis/gopath/src/github.com/go-graphite/go-carbon/carbonserver/carbonserver.go:921 +0x73\npanic(0xe88200, 0xc1f5ed1920)\n\t/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/panic.go:969 +0x1b9\ngithub.com/go-graphite/go-carbon/carbonserver.(*gdstate).step(0xc5f7e69360, 0xd0, 0xc5f74ec980)\n\t/home/travis/gopath/src/github.com/go-graphite/go-carbon/carbonserver/trie.go:112 +0x185\ngithub.com/go-graphite/go-carbon/carbonserver.(*trieIndex).query(0xc56b077b80, 0xc2f63e63c0, 0x34, 0x7530, 0xc000257b40, 0x1, 0x5, 0xc2f63e63c0, 0x34, 0xc04bcca5d8, ...)\n\t/home/travis/gopath/src/github.com/go-graphite/go-carbon/carbonserver/trie.go:613 +0x7e8\ngithub.com/go-graphite/go-carbon/carbonserver.(*CarbonserverListener).expandGlobsTrie(0xc000416000, 0xc2f63e6300, 0x34, 0xc2f63b9ce0, 0x4164573172306167, 0x7064374c76544162, 0x69682f52484c2f49, 0x6f635f6275735f74, 0x7073772e746e75, 0x0, ...)\n\t/home/travis/gopath/src/github.com/go-graphite/go-carbon/carbonserver/trie.go:1177 +0x2d9\ngithub.com/go-graphite/go-carbon/carbonserver.(*CarbonserverListener).expandGlobs(0xc000416000, 0x1040340, 0xc785c85380, 0xc2f63e6300, 0x34, 0
Oct 20 20:59:28 hostname go-carbon[209316]: xc2f63b9c20)\n\t/home/travis/gopath/src/github.com/go-graphite/go-carbon/carbonserver/carbonserver.go:945 +0x1fa\ncreated by github.com/go-graphite/go-carbon/carbonserver.(*CarbonserverListener).getExpandedGlobs\n\t/home/travis/gopath/src/github.com/go-graphite/go-carbon/carbonserver/find.go:337 +0xf5\n"}]}
Oct 20 20:59:28 hostname go-carbon[209316]: {"level":"ERROR","timestamp":"2020-10-20T20:59:28.588Z","logger":"access","message":"fetch failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:57648","carbonapi_uuid":"975b2d17-9969-4cab-99bb-c3f45716f80d","carbonzipper_uuid":"975b2d17-9969-4cab-99bb-c3f45716f80d","format":"carbonapi_v3_pb","targets":["foo.bar.requests"],"runtime_seconds":0.000224746,"reason":"failed to read data","http_code":400,"error":"find failed, can't expand globs"}
```

**Comment by bom-d-van** [comment]
Hi @obfuscurity what was the current version running on your production? Trie is released in v0.15.0. It should be an issue since trie was introduced if my understanding is correct.

It appears that there is a non-ascii character in your query which crashes the query. Would it be possible for you share the actual query? I supposed it's not really `foo.bar.requests`, right?

But I will make a patch to guard against the crash for sure.

edit: and thanks for testing and sharing the error logs!

**Comment by bom-d-van** [comment]
Oh, maybe it"s because of non-ascii characters in the metric names, need to double check for making sure.

**Comment by obfuscurity** [comment]
We've been running 0.14.0 in production for a while, and with trie index enabled / trigram disabled since June 2020. We dropped in 0.15.0 / 0.15.3 with no changes to our configuration.

Of the four output lines I pasted above, the original metric strings were entirely ascii characters. We certainly have non-ascii characters in many of our other metrics, but none in the metrics used in this report.

I'm still confused as to why we're seeing the `find failed, can't expand globs` error, given that _there are no globs_ in the query.

**Comment by obfuscurity** [comment]
Ok we did some more digging and determined you're correct wrt trie index... we _enabled_ it back in June, but presumably that config setting was ignored bc that feature wasn't shipped until 0.15.0 (we must have accidentally referred to master docs). All that really happened was that we disabled trigram index.

I've disabled trie index on 0.15.3 on our test system and confirmed that things are working again. I'd like to understand why trie is failing for us, but this should be adequate for us to push forward with 0.15.0 / 0.15.3 on our production systems [with both indexes disabled].

**Comment by bom-d-van** [comment]
Thanks for confirming it. I think it's because we don't allow non-ascii texts in metric names and queries on our deployment so I didn't include the support in the trie implementation. I remember I had also read it on https://graphite.readthedocs.io/ but I can't find it now, maybe I was "drunk". :P

But I think it should be possible to support non-ascii in trie index and I will also make sure it doesn't panics because of that.

**Comment by obfuscurity** [comment]
@bom-d-van I'll only mention it here bc of the existing thread, but we effectively had to failback both carbonapi and go-carbon after users reported problems with globbing/sorting functions. I'll open up a separate bug against the relevant project once we diagnose further, but suffice it to say this was a frustrating couple of days. :(

**Comment by deniszh** [comment]
@obfuscurity : that's sad to hear that! 
Did you disable both indices and still using carbonserver or did I misunderstand your setup?
TBH I'm not sure how that configuraton will work...

**Comment by obfuscurity** [comment]
Yes, we've disabled both trigram and trie indices. We've effectively been running this configuration successfully since June.

**Comment by bom-d-van** [comment]
> but suffice it to say this was a frustrating couple of days. :(

Sorry to hear that. Probably due to configuration/deployment differences, other than the latest concurrent trie features, v.0.15.0+ is running fine on our environment as far as I know. Unless maybe it's some issues we don't know about.

> users reported problems with globbing/sorting functions. I'll open up a separate bug against the relevant project once we diagnose further

Yeah, please let us know when you have more information. I'm sure we can sort it out if we understand what's the issue.

**Comment by bom-d-van** [comment]
Hi @obfuscurity I have pushed some fixes for supporting non-ascii texts in filenames and queries. With this, you should be able to use trie-index on your production env.

**Comment by deniszh** [comment]
Cool, merged to master. Let me quickly make bugfix release.

**Comment by bom-d-van** [comment]
@deniszh thank you!

**Comment by deniszh** [comment]
0.15.4 released

**Comment by obfuscurity** [comment]
Apologies for the delayed response. We've only recently been able to circle back around to this. After upgrading carbonapi and confirming everything looks good _there_, I've upgraded a single node to go-carbon 0.15.6 and resumed testing. It does appear that the original issue as described ("can't expand globs") has been resolved. However, it appears that we're still hitting other issues wrt unicode characters in metric names.

We're running 0.15.6 on this node with trie index enabled and trigram disabled. Here is a sequence where we drilled into the metric path (using Grafana explore, via carbonapi). You can see that as soon as it encounters any affected names (via glob or direct), it returns some (apparently upstream golang) errors.

```
Jun 01 17:01:24 <hostname> go-carbon[60145]: {"level":"ERROR","timestamp":"2021-06-01T17:01:24.016Z","logger":"access","message":"fetch failed","handler":"render","url":"/render/?format=carbonapi_v3_pb","peer":"127.0.0.1:39010","carbonapi_uuid":"9d62ab09-4227-458f-85b4-cca6bd594ac7","carbonzipper_uuid":"9d62ab09-4227-458f-85b4-cca6bd594ac7","format":"carbonapi_v3_pb","targets":["metrics.base.path"],"runtime_seconds":0.000249668,"reason":"no metrics found","http_code":404}
Jun 01 17:01:25 <hostname> go-carbon[60145]: {Metrics:[metrics.base.path.*] XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}
Jun 01 17:02:11 <hostname> go-carbon[60145]: {Metrics:[metrics.base.path.<unicode string>.<metric>] XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}
```

Happy to open a separate issue if you all feel like this is an actual bug.

**Comment by bom-d-van** [comment]
Hi @obfuscurity , yeah, hehe, it's being a while. Glad to hear that the original bug is fixed for you.

Could you include a bit more information for the new issue? I'm not sure what's the problem here as there is no error returned by go-carbon in your truncated log, and it just says: `no metrics found`, which isn't necessarily an error.

Or are you saying that go-carbon can't find or render metrics with unicode chars?

Just in case, there is some unicode configs/control in carbonapi as well.

**Comment by obfuscurity** [comment]
The `no metrics found` "error" isn't a problem, it's simply stating there were no metrics in that parent directory (correct). The problem is the successive lines with the `XXX_NoUnkeyedLiteral` message. These queries work in our other go-carbon 0.14.x nodes with trie index disabled.

**Comment by bom-d-van** [comment]
Hmm, are there other logs around the `XXX_NoUnkeyedLiteral` lines? That's new to me.

**Comment by obfuscurity** [comment]
There were no other logs but we were logging at `level = "warn"`. Would it help for me to increase logging output?

**Comment by bom-d-van** [comment]
Yes, we should be able to see more info for that.

Can't really figure out what's the issue here with the XXX_NoUnkeyedLiteral message alone.

**Comment by bom-d-van** [comment]
`"debug"` would be better.

**Comment by obfuscurity** [comment]
Apologies, it looks like this was a false positive on my end. Known good metrics with unicode in the name are indeed able to be retrieved successfully. I'm still a little curious about those `XXX_NoUnkeyedLiteral` entries in the `warn` logs, but it doesn't seem to correlate with any regression here.

**Comment by bom-d-van** [comment]
Cool, glad to hear there is no new issue.

> I'm still a little curious about those XXX_NoUnkeyedLiteral entries in the warn logs, but it doesn't seem to correlate with any regression here.

Yep, that's a bit odd.

**Comment by Civil** [comment]
That XXX_NoUnkeyedLiteral might be related to: https://github.com/go-graphite/protocol/commit/ec66858bcd41d96d7fd8aac4ffcc643763ad2cfd

Currently pinned https://github.com/go-graphite/go-carbon/blob/master/go.mod#L21 version is below that and there were two new fields introduced (and go-graphite/carbonapi uses them now).

Though good thing about that is that they do not matter much for go-carbon (could be somehow useful to take them into account if there is a graphite-web 1.1.x pointing to carbonapi, but that's not a hard requirement though)

**Comment by obfuscurity** [comment]
Adding another note after some recent debugging. Turns out when we upgraded from 0.14.x to 0.15.x, we missed seeing the new `max-metrics-rendered` setting. The low default (1000) was causing responses to be incomplete, which in turn affected carbonapi transforms like `highestAverage()`. This made it appear that sets were being sorted e.g. alphanumerically, since go-carbon was only returning a very small subset of the overall request.

IMHO this setting should have had a _very_ explicit callout in the CHANGELOG. It certainly would have saved us days of debugging.

**Comment by bom-d-van** [comment]
Thanks for the feedback @obfuscurity .

When it was introduced, I thought 1000 should be high enough. Turns out we do have users prefer higher limit by default.

How does 5k look like to you?

I can see if I can edit the release log.

**Comment by obfuscurity** [comment]
I can't really speak to what a sane default might be. I think the issue here is less about the value and more about making sure folks are _aware_ of it during the upgrade cycle. Hopefully it's far enough in the past that it won't matter for most other users.

But in our case, the one query that surfaced this issue was returning almost 30k metrics. I don't think we have a good way of measuring per-query metric numbers (this would be a useful metric to export imho, either in go-carbon or carbonapi), so for now we're erring on the side of caution and increasing our setting to 100k.

**Comment by bom-d-van** [comment]
>  I think the issue here is less about the value and more about making sure folks are aware of it during the upgrade cycle. 

Yep, you are right. Thanks for the suggestion. 

>  I don't think we have a good way of measuring per-query metric numbers (this would be a useful metric to export imho, either in go-carbon or carbonapi), so for now we're erring on the side of caution and increasing our setting to 100k.

There should be some logs from go-carbon access indicating the number of metrics returned. But yes, exporting some usage metrics would be good.
Maybe generating an error log or even return errors in go-carbon or carbonapi might be good.
