### ISSUE TITLE
Go-carbon in different DC.

### ISSUE THREAD

**Issue by colixxx** [go-graphite/go-carbon#392]
Hey. 
I have 2 go-carbon clusters in different DCs. To see metrics from applications from different DCs in one Grafana dashboard, I added carbonapi in the second DC as a backend to carbonapi in the first DC. Since in carbonapi lbMethod: "broadcast" go-carbon from the second DC accepts a lot of requests from the first DC and cannot find metrics, since they are not there. 

**Log from carbonapi:**
```
{"level":"WARN","timestamp":"2020-12-17T07:42:03.089Z","logger":"slow","message":"Slow Request","time":1.34
3725006,"url":"https:///render/?format=protobuf&from=1608190518&target=stats.timers.python......&until=1608190818","referer":""}
```

**go-carbon in second DC**
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/55874175/102458678-a89a1480-4055-11eb-853e-913baf8533fe.png">

**go-carbon in first DC:**
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/55874175/102458791-c9fb0080-4055-11eb-8a9f-02cbc436179a.png">

The number of incoming metrics is different, but the number of requests is the same.

Question: is there a setting in go-carbon that will allow you not to search every time for a metric that is not there? can you cache the response?

**go-carbon.conf**
```
[common]
user = "root"
graph-prefix = "carbon.agents.{host}"
metric-endpoint = "local"
max-cpu = 1
metric-interval = "1m0s"

[whisper]
data-dir = "/data/graphite/whisper/"
schemas-file = "/etc/go-carbon/storage-schemas.conf"
aggregation-file = "/etc/go-carbon/storage-aggregation.conf"
workers = 1
max-updates-per-second = 0
max-creates-per-second = 0
hard-max-creates-per-second = false
sparse-create = false
flock = false
enabled = true
hash-filenames = true
remove-empty-file = true

[cache]
max-size = 1000000
write-strategy = "max"

[udp]
listen = ":2103"
enabled = true
buffer-size = 0

[tcp]
listen = ":2103"
enabled = true
buffer-size = 0
compression = ""

[pickle]
listen = ":2004"
max-message-size = 67108864
enabled = true
buffer-size = 0

[carbonlink]
listen = ":7002"
enabled = true
read-timeout = "30s"

[grpc]
listen = ":7003"
enabled = true

[tags]
enabled = false
tagdb-url = "http://:8000"
tagdb-chunk-size = 32
tagdb-update-interval = 100
local-dir = "/srv/graphite/tagging/"
tagdb-timeout = "1s"

[carbonserver]
listen = ":8080"
enabled = true
query-cache-enabled = true
query-cache-size-mb = 0
find-cache-enabled = true
buckets = 10
max-globs = 100
fail-on-max-globs = false
metrics-as-counters = false
trigram-index = true
internal-stats-dir = ""
read-timeout = "1m0s"
idle-timeout = "1m0s"
write-timeout = "1m0s"
scan-frequency = "5m0s"

[dump]
enabled = false
path = "/srv/graphite/dump/"
restore-per-second = 0

[pprof]
listen = ":7007"
enabled = false

[[logging]]
logger = ""
level = "error"
encoding = "json"
encoding-time = "iso8601"
encoding-duration = "seconds"
sample-tick = ""
sample-initial = 0
sample-thereafter = 0

[prometheus]
enabled = false
endpoint = "/metrics"
[prometheus.labels]

```

**Comment by deniszh** [comment]
Hi @radinv,

"Slow Request" log line means slow request (more then 1 second IIRC).
You just need to add both go-carbons to single carbonapi as backends - should work fine, it's normal mode.

Let's continue in https://github.com/go-graphite/carbonapi/issues/547, I think this issue is not related to go-carbon.
