### ISSUE TITLE
[Q] Utilities to explore the whiser DB

### ISSUE THREAD

**Issue by ervikrant06** [go-graphite/go-carbon#393]
Python implementation of carbon provides following utilites to work with whisper DB. Is any such utility available in go-carbon implementation? I am using Dockerfile from go-carbon project to create the docker image.  

`# ./whisper-
whisper-auto-resize.py             whisper-dump.py                    whisper-merge.py                   whisper-update.py
whisper-auto-update.py             whisper-fetch.py                   whisper-resize.py
whisper-create.py                  whisper-fill.py                    whisper-set-aggregation-method.py
whisper-diff.py                    whisper-info.py                    whisper-set-xfilesfactor.py
`

**Comment by deniszh** [comment]
Go-carbon not provides compatible utilities for whisper files. Python utilities are compatible, though and should be installable with 'pip install whisper' (if python and pip are present ofc)

**Comment by Civil** [comment]
Some of the utils provided as part of buckytools package: https://github.com/go-graphite/buckytools

**Comment by azhiltsov** [comment]
@ervikrant06 you can also find some tools in go-whisper lib
https://github.com/go-graphite/go-whisper/tree/master/cmd

**Comment by ervikrant06** [comment]
thanks guys, comments were very helpful.
