### ISSUE TITLE
[Q] change in fidelity/resolution/smoothness of graph data migrating from graphite-cabon -> go-carbon

### ISSUE THREAD

**Issue by brad-plumewifi** [go-graphite/go-carbon#402]
Environment:
Grafana 7.x 
Ubuntu Linux 16.04
previous version -> graphite-carbon 0.9.15-1 
updated version -> go-carbon 0.15.6
graphite-web  -> 0.9.15+debian-1

Following a migration to go-carbon from graphite-carbon, the smoothing in a number of my Grafana graphs has disappeared and has become spotty/choppy.  Not sure if this means data isn't making it into cache or disk on time, or if data is being dropped, or the graphite function has changed to calculate the sum/avg.  

[go-carbon.conf.txt](https://github.com/go-graphite/go-carbon/files/5992472/go-carbon.conf.txt)

![go-carbon](https://user-images.githubusercontent.com/29928973/108139509-0d351800-7075-11eb-917a-8316a462d447.png)

The relevant query is 
alias(sumSeries(nonNegativeDerivative($a.$component-$deployment*.$longPerfdataNamespaceQuery.value, 0)), 'Messages Received')

Attached go-carbon.conf 

Any help is appreciated.  Thanks in advance :)

**Comment by bom-d-van** [comment]
Hi @brad-plumewifi , have you check the values of each individual metrics, without aggregating it? Is it still matching to the values that it's produced? If it is, then the issue probably not on go-carbon.

You can also check if there is any data lost due to [cache size](https://github.com/go-graphite/go-carbon#reported-stats), (the metric isn't documented but it's reported): `cache.overflow`.

**Comment by brad-plumewifi** [comment]
Thanks for your reply @bom-d-van 

Does this mean I'm losing over 600k data points? :)

![image](https://user-images.githubusercontent.com/29928973/108258374-c696fa80-7114-11eb-811f-051d8f1d1005.png)

**Comment by bom-d-van** [comment]
Yes, I think so. How about the `cache.queueWriteoutTime` and `cache.metrics`? 

The `max-size` in `[cache]` is default 2000000, you can increase it. Probably also check the memory usage for your go-carbon instance, just to be sure there is enough memory.

Maybe also adjust the default in `[whisper]`:

```
[whisper]
max-updates-per-second = 500
max-creates-per-second = 50
```

**Comment by brad-plumewifi** [comment]
![image](https://user-images.githubusercontent.com/29928973/108468206-37d0cd80-723b-11eb-8357-9c87fe56bd3f.png)

**Comment by deniszh** [comment]
@brad-plumewifi : could you please put your old Graphite's carbon.conf somewhere and put link here please?

**Comment by brad-plumewifi** [comment]
Hi guys -- increasing the max-size cache fixed it.  Evictions (or overflow) have dropped down to 0 and the number of overall items in the cache increased by 100k.  All my original graphs have recovered.  I increased updates and creates per second and it looks like write-out time has decreased by a bit too. 

![image](https://user-images.githubusercontent.com/29928973/108985846-5c1b1880-7646-11eb-8eea-6166bab1fce0.png)

![image](https://user-images.githubusercontent.com/29928973/108985622-1cecc780-7646-11eb-8511-ac789f60a8ab.png)

Thanks a ton for your help -- appreciate it!
