### ISSUE TITLE
go-carbon not logging metrics

### ISSUE THREAD

**Issue by rickyari** [go-graphite/go-carbon#418]
our go-carbon cluster has 9 nodes and currently we are not able to see any data on grafana. It seems that persisters are not logging any data to disk. I have formatted the underlying disk on one of the servers but the metrics are logged for a brief period and again the metrics are lost. On checking logs(/var/log/go-carbon/go-carbon.log) I can see that persister is not able to write metrics complaining file name too long. Please help as the whole graphite cluster is unstable right now.

```2021-07-21T06:08:15.168Z] ERROR [persister] failed to open whisper file {"path": "/mnt/array1/graphite/whisper/stats/hcom-prod-decaf/us-east-1/backend/gauges/oneapi-loom/_worker-0/meters/circuit/user-preferences-schema-service/addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty/success/m5_rate.wsp", "error": "open /mnt/array1/graphite/whisper/stats/hcom-prod-decaf/us-east-1/backend/gauges/oneapi-loom/_worker-0/meters/circuit/user-preferences-schema-service/addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty/success/m5_rate.wsp: file name too long"}```

**Comment by rickyari** [comment]
Would somebody be able to help. Our prod cluster is degraded due to this issue.

**Comment by deniszh** [comment]
If only some of metrics have very long name - that should not block other metrics to persist. But if all of them looks like above - then it will not work.
Anyway, go-carbon can't do much in this case. It tries to write file to disk and if metric name is too long - it will fail.
I can only advice to install carbon-c-relay with proper -m value - that will discard metrics with long name.

https://github.com/grobian/carbon-c-relay

**Comment by rickyari** [comment]
@deniszh Thanks for the reply. 
So what should be my approach for troubleshooting this issue as I can see no new metrics is being written to disk and I am sure we  have different metrics coming in for different apps and they do not resemble the error metrics as seen in past. Could there be some issues with go-carbon persisters as they are not able to store data to disk.
 Or is there a way to see incoming metrics on carbon-c-relay servers.

**Comment by deniszh** [comment]
I'm AFK currently and can't check sources thoroughly. Maybe constantly failing workers are not able to write legitimate metrics. 
If you already using carbon-c-relay you can restart it with -m 4032 - this will discard error metrics automatically.
For debugging you can make another cluster in carbon-c-relay with type "file" and send copy of all metrics to that file. But please take note that for busy installations that could fill up disk quite fast.

**Comment by bom-d-van** [comment]
@rickyari are you sure it's an issue in go-carbon? is it possible that there are changes in your metric producer that generates corrupted metric path like the one you posted: 

```
addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty_addFavouriteProperty
```

And linux has a maximum file name length of 255 and a maximum path of 4096.

**Comment by bom-d-van** [comment]
Try add some logs in your metric producer, and see if the metric paths are being generated properly.

**Comment by rickyari** [comment]
Thanks for your comments.

This is the process that is running on one of the carbon-c-relay servers
```/usr/bin/carbon-c-relay -f /etc/carbon-c-relay.conf -p 2004 -w 8 -b 2500 -q 300000```

And we start the carbon-c-relay service via systemctl. Shall I stop the service and start it manually by adding the -m flag on command line.

**Comment by deniszh** [comment]
Probably that didn't help. Looks like it's complaining not about full path more then 4096 bytes, but one of its directories more then 255 bytes, as @bom-d-van suggested.
Also, it's not clear is it related for your issues at all. :(
But you can try, of course - but we can't suggest how to operate carbon-c-relay and/or systemd, unfortunately.

**Comment by rickyari** [comment]
@deniszh @bom-d-van  Thank you for your inputs on this. I have managed to recover the nodes. The issue was that the nodes were hitting internal cache limit due to which go-carbon was not running as expected. Maybe an increase in incoming metrics triggered this event. I have to increase the cache limit which for now has resolved the issue.
