### ISSUE TITLE
Support aggregation-rules.conf

### ISSUE THREAD

**Issue by hnakamur** [go-graphite/go-carbon#42]
First of all, thanks for sharing a nice software!

I would like to sum up multiple metrics (the same metric from multiple servers) and save to another metric. I would like to keep the original metrics from multiple servers and the sum alongside them.
I read the document of the original carbon and found it is supported in [aggregation-rules.conf](http://graphite.readthedocs.org/en/latest/config-carbon.html#aggregation-rules-conf).

So I wish a support of aggregation-rules.conf in go-carbon too!
If you are busy, I will try to write a pull request for that.

**Comment by lomik** [comment]
Hi, 

Try one of the external aggregator:
https://github.com/grobian/carbon-c-relay
https://github.com/github/brubeck
https://github.com/etsy/statsd
https://github.com/bitly/statsdaemon

I do not have plan to realize aggregation inside carbon.

**Comment by hnakamur** [comment]
@lomik Thanks for your suggestion.
I will look into those aggregators.

**Comment by lomik** [comment]
I forgot about https://github.com/armon/statsite

**Comment by lomik** [comment]
Not planned. Use external aggregator

**Comment by superopsdev** [comment]
how to solve this problem，at last

**Comment by Civil** [comment]
@superman1qaz Use carbon-c-relay, carbon-relay-ng or statsd (or anything else that can have graphtie line protocol as input and graphite line protocol as output)

As an alternative you can do aggregation on a render side. You send all data as-is to the go-carbon and apply aggregation functions when querying them on graphite-web/graphite-api/carbonapi side.
