### ISSUE TITLE
FAIL: TestThrottleChan on some machines (i.e. in virtualbox)

### ISSUE THREAD

**Issue by Slach** [go-graphite/go-carbon#44]
When i try make deb package over 

<pre>
git checkout
git submodules init
git submodules update
make clean && make && make deb
</pre>

i have following error on some machines

<pre>
 --- FAIL: TestThrottleChan (8.00 seconds)
     assertions.go:156:
     Location:       throttle_test.go:38
     Error:          Should be true
     Messages:       perSecond: 1000, bw: 822
</pre>

possible reason it happening when machine have too small CPU resources
do you have .deb PPA ? or maybe i can skip test? or maybe need increase minimum for throttling?

**Comment by lomik** [comment]
Hi. Thanks for fix. But I think better add the ability to skip throttling test.

**Comment by lomik** [comment]
https://github.com/lomik/go-carbon/commit/48b183760ff658145e1013e037428f5b03ce5652
go test disabled for build deb. Long wanted

**Comment by Slach** [comment]
thanks a lot ;)
