### ISSUE TITLE
Aggregation not worked?

### ISSUE THREAD

**Issue by Slach** [go-graphite/go-carbon#46]
i have following go-carbon.conf

<pre>
[common]
user = "monitor"
logfile = "/var/log/go-carbon/go-carbon.log"
log-level = "info"
graph-prefix = "carbon.agents.{host}."
max-cpu = 8
metric-interval = "1m0s"

[whisper]
data-dir = "/opt/graphite/storage/whisper/"
schemas-file = "/opt/graphite/conf/storage-schemas.conf"
aggregation-file = "/opt/graphite/conf/storage-aggregation.conf"
workers = 8
max-updates-per-second = 0
sparse-create = true
enabled = true

[cache]
max-size = 1000000
input-buffer = 1000000

[udp]
listen = "127.0.0.1:2013"
enabled = true
log-incomplete = false

[tcp]
listen = "127.0.0.1:2013"
enabled = true
log-incomplete = true

[pickle]
listen = "127.0.0.1:2014"
max-message-size = 67108864
enabled = true

[carbonlink]
listen = "127.0.0.1:7002"
enabled = true
read-timeout = "30s"
query-timeout = "100ms"

[pprof]
listen = "localhost:7007"
enabled = false
</pre>

and following aggregation rules

<pre>
pinba.total.traffic_per_sec (60) = sum pinba.&lt;host&gt;.&lt;server&gt;.&lt;script&gt;.traffic_per_sec
pinba.total.req_count (60) = sum pinba.&lt;host&gt;.&lt;server&gt;.&lt;script&gt;.req_count

pinba.total.req_50_percentile (60) = max pinba.*.*.*.req_50_percentile
pinba.total.req_90_percentile (60) = max pinba.*.*.*.req_90_percentile
pinba.total.req_95_percentile (60) = max pinba.*.*.*.req_95_percentile
pinba.total.req_98_percentile (60) = max pinba.*.*.*.req_98_percentile

pinba.total.error_count   (60) = sum pinba.*.*.*.error_count
pinba.total.error_percent (60) = avg pinba.*.*.*.error_percent

pinba.total.tag_by_req (60) = sum pinba.*.*.*.*.*.tag_by_req_avg
pinba.total.tag_req_percent (60) = avg pinba.*.*.*.*.*.tag_req_percent

pinba.total.req_less_02s (60) = sum pinba.*.*.*.req_less_02s
pinba.total.req_02s_05s (60) = sum pinba.*.*.*.req_02s_05s
pinba.total.req_05s_1s (60) = sum pinba.*.*.*.req_05s_1s
pinba.total.req_1s_2s (60) = sum pinba.*.*.*.req_1s_2s
pinba.total.req_more_2s (60) = sum pinba.*.*.*.req_more_2s

pinba.total.tag_less_01s (60) = sum pinba.*.*.*.*.*.tag_less_01s
pinba.total.tag_01s_02s (60) = sum pinba.*.*.*.*.*.tag_01s_02s
pinba.total.tag_02s_05s (60) = sum pinba.*.*.*.*.*.tag_02s_05s
pinba.total.tag_05s_1s (60) = sum pinba.*.*.*.*.*.tag_05s_1s
pinba.total.tag_more_1s (60) = sum pinba.*.*.*.*.*.tag_more_1s

pinba.total.tag_50_percentile (60) = max pinba.*.*.*.*.*.tag_50_percentile
pinba.total.tag_90_percentile (60) = max pinba.*.*.*.*.*.tag_90_percentile
pinba.total.tag_95_percentile (60) = max pinba.*.*.*.*.*.tag_95_percentile
pinba.total.tag_98_percentile (60) = max pinba.*.*.*.*.*.tag_98_percentile
</pre>

pinba.\* metrics received on port 2013 and i see this traffic over 

<pre>
tcpdump -i lo -w go-carbon.pcap port 2013 and host 127.0.0.1
</pre>

see http://take.ms/qS34T

but pinba.total.\* metrics in wsp files don't  updates

in go-carbon.log i don't see any errors about incorrect aggregation rules, how i can debug and fix it this problem?

**Comment by lomik** [comment]
http://graphite.readthedocs.io/en/latest/config-carbon.html#storage-aggregation-conf is not http://graphite.readthedocs.io/en/latest/config-carbon.html#aggregation-rules-conf

"Aggregation rules" not supported. Try external aggregators https://github.com/lomik/go-carbon/issues/42
