### ISSUE TITLE
Memory use very high

### ISSUE THREAD

**Issue by gkramer** [go-graphite/go-carbon#473]
Current setup:

* 16C CPU
* 32GB RAM Machine
* 32GB Swap (Added today)
* Approx 27TB of whisper files

Memory utilisation seems to grow uncontrollably - I've reduced the number of workers to 4, and modified a few other values to see what impact this would have, but daemon is still killed every 2-3h by the kernel.

Is there any way to artificially limit the amount of memory the daemon consumes - high and low water limit, perhaps? Any other suggestions in this regard would be great. In the meantime, I have a process that restarts the daemon on failure, but I'm concerned about data loss when the daemon fails, so this isnt a long-term solution.

Any assistance would be appreciated.

Thanks,
G

**Comment by bom-d-van** [comment]
hi @gkramer , can you share the go-carbon config and the number of metrics?

**Comment by gkramer** [comment]
`[common]
user = "graphite"
graph-prefix = "carbon.agents.{host}"
metric-endpoint = "local"
metric-interval = "1m0s"
max-cpu = 4

[whisper]
data-dir = "/data/graphite/storage/whisper"
schemas-file = "/data/graphite/conf/storage-schemas.conf"
aggregation-file = "/data/graphite/conf/storage-aggregation.conf"
workers = 4
max-updates-per-second = 0
max-creates-per-second = 0
hard-max-creates-per-second = false
sparse-create = false
flock = true
enabled = true
hash-filenames = true


compressed = false
remove-empty-file = false


[cache]
max-size = 100000    # 1000000

write-strategy = "max"

[udp]
listen = ":2503"
enabled = true
buffer-size = 0

[tcp]
listen = ":2503"
enabled = true
buffer-size = 0

[pickle]
listen = ":2504"
max-message-size = 67108864
enabled = true
buffer-size = 0


[carbonlink]
listen = "127.0.0.1:7502"
enabled = true
read-timeout = "30s"

[grpc]
listen = "127.0.0.1:7503"
enabled = true

[tags]
enabled = false
tagdb-url = "http://127.0.0.1:8000"
tagdb-chunk-size = 32
tagdb-update-interval = 100
local-dir = "/var/lib/graphite/tagging/"
tagdb-timeout = "1s"

[carbonserver]
listen = "127.0.0.1:8080"
enabled = true
buckets = 10
metrics-as-counters = false
read-timeout = "60s"
write-timeout = "60s"
query-cache-enabled = true
query-cache-size-mb = 1000  # FIXME: Was: 0
find-cache-enabled = true
trigram-index = true
scan-frequency = "5m0s"
trie-index = false

file-list-cache = ""

concurrent-index = false

realtime-index = 0

max-inflight-requests = 0

no-service-when-index-is-not-ready = false

cache-scan = false

max-globs = 100
fail-on-max-globs = false

max-metrics-globbed  = 30000
max-metrics-rendered = 1000

graphite-web-10-strict-mode = true

empty-result-ok = false

internal-stats-dir = ""
stats-percentiles = [99, 98, 95, 75, 50]

[dump]
enabled = false
path = "/var/lib/graphite/dump/"
restore-per-second = 0

[pprof]
listen = "localhost:7007"
enabled = false

[[logging]]
logger = ""
file = "/var/log/go-carbon/go-carbon.log"
level = "debug"
encoding = "mixed"
encoding-time = "iso8601"
encoding-duration = "seconds"`

-------

Currently, the daemon falls over without any metrics (outside of carbon-relay-ng + go-carbon) passing through it. However, on-disk wsp files take up approx 25-27TB of storage.

Does the daemon currently pull whisper files into memory? Thats the only thing I can think of which would cause memory to ramp up to now 41GB virt and 25.6GB res memory.

**Comment by bom-d-van** [comment]
> However, on-disk wsp files take up approx 25-27TB of storage.
the size of the whisper files are one thing. for memory consumption, one important part is the number of whisper files (i.e. metrics) because of indexing it.

> Does the daemon currently pull whisper files into memory? Thats the only thing I can think of which would cause memory to ramp up to now 41GB virt and 25.6GB res memory.

you are current using trigram index. you can try disabling it or enableing `trie-index = true`. trie index might have better memory utilisation and faster indexing during restart. also consider using `no-service-when-index-is-not-ready = true` if using trie-index.

without indexing, go-carbon should uses less memories but find and render queries might be slower.

**Comment by gkramer** [comment]
@bom-d-van Thanks, I've turned off trigram-index, and will see what impact that has for now. If that doesnt work, I'll enable it along with trie-index and no-service.

Any other suggestions?

Does the daemon scrape metrics from the disk that havent been 'seen' yet? If so, where does it stop doing so if theres an enormous amount? Surely there should be a high-water mark of sorts with prioritization given to highest touch metrics?

**Comment by bom-d-van** [comment]
> Does the daemon scrape metrics from the disk that havent been 'seen' yet? If so, where does it stop doing so if theres an enormous amount? Surely there should be a high-water mark of sorts with prioritization given to highest touch metrics?

`scan-frequency` controls how frequently does go-carbon scan the file tree for indexing files. If there are too many metrics on disk, it doesn't stop on its own.

Other options:

- You might have to consider scaling out, instead of keeping all the metrics in one box
- raise up the memory for the server
- peoridically remove stale metrics with find

You need to figure out how many data points you are receiving and how many active metrics you are saving. go-carbon exports metrics for that. linux also needs memory for page cache.

**Comment by gkramer** [comment]
@bom-d-van Thanks for your help! I've decided to turn off indexing, as its more economical to do so than to add 100's of GB of RAM to the machine - we've got 30+TB of data on disk, and cant justify indexing all of it right now.

**Comment by gkramer** [comment]
As above.
