### ISSUE TITLE
[Q] Why the online config/schema migration tool isn't running?

### ISSUE THREAD

**Issue by BorisMan9** [go-graphite/go-carbon#477]
Hi,
I enabled the online migration tool in `go-carbon.conf` (also increased the migration rate):

> online-migration = true
online-migration-rate = 50000

I made a change in `storage-schemas.conf`, increased the retention from `10s:1h,1m:7d,10m:14d` to `10s:1h,1m:7d,10m:30d,1h:70d`

new whisper filles are created with the correct retention but old whisper files wont migrate to the new retentions config. can anyone help me figure out why is it that the migration tool wont resize the old whisper files?

thanks

go version: 1.10.4
go-carbon version: 0.16.2

**Comment by bom-d-van** [comment]
hi, I think you might have to build go-carbon against master to use the feature. The changes were merged but we haven't made a new release yet.

**Comment by BorisMan9** [comment]
understood, so I need to resize manually
is it possible to upgrade my go-carbon version if I want to retain my data (config + whisper files)?
or I must uninstall and install a clean version?

**Comment by bom-d-van** [comment]
> is it possible to upgrade my go-carbon version if I want to retain my data (config + whisper files)?
> or I must uninstall and install a clean version?

Yeah, you just need to build a new binary and replace it directly. You can keep your config and data. It's backward-compatible.

**Comment by BorisMan9** [comment]
because you haven't released a new version yet (that includes the online migration tool) I need to build manually from `master` branch, and for that I need to upgrade go version to 1.8+, right?
can you tell if upgrading go version to 1.8+ may interfere with latest version of go-graphite/carbonapi?

**Comment by bom-d-van** [comment]
> because you haven't released a new version yet (that includes the online migration tool) I need to build manually from master branch, and for that I need to upgrade go version to 1.8+, right?

Yes, for that we need go `1.18+`.

> can you tell if upgrading go version to 1.8+ may interfere with latest version of go-graphite/carbonapi?

Oh, yeah, it's all good. we are using master build on our production.

**Comment by borisman4** [comment]
Ok great
Thanks a lot!

**Comment by BorisMan9** [comment]
Ok great, thanks a lot!
