### ISSUE TITLE
support for multiple go-carbon caches

### ISSUE THREAD

**Issue by dopey** [go-graphite/go-carbon#49]
Hi,

I think this question is more suited for a mailing list, as its not actually an issue.

With graphite/carbon I am able to support multiple caches within a single process. Is their a way to do this with go-carbon or is the prescribed method to run multiple instances of go-carbon.

cheers,
max

**Comment by johnseekins** [comment]
The idea behind go-carbon is that it is actually multi-threaded, so you don't need multiple versions running. Carbon caches are single-threaded processes, so splitting out to multiple processes becomes necessary quite quickly.

**Comment by dopey** [comment]
Ah, did not know that. 

I found an example that generated multiple instances of go-carbon on the same machine and figured that was a necessity for parallelization. Appreciate the explanation.

cheers,
max

**Comment by lomik** [comment]
@johnseekins gave the correct answer. Just increase `max-cpu` (in `common` group) and `workers` (in `whisper`).
