### ISSUE TITLE
creates.log

### ISSUE THREAD

**Issue by rtoma** [go-graphite/go-carbon#50]
I am planning on migrating a carbon-cache (~80k points/sec) setup to go-carbon.

I like to track what whisper files are being created to detect if high cardinality identifiers (e.g. session-ids, user-ids, order-id) are used in the metrics names.

Example of carbon-cache's creates.log:

```
08/06/2016 08:56:49 :: creating database file /opt/graphite/storage/whisper/a/b/c.wsp (archive=[(60, 11520), (300, 9216), (900, 17280), (1800, 27600)] xff=None agg=None)
```

Could you maybe implement something similar in go-carbon?

**Comment by lomik** [comment]
All creates tracked to main log with log-level = "debug". Maybe that's enough?

**Comment by rtoma** [comment]
Oh, you're right!

Depending how active the other debug logger are, this will work.

For future readers the "create" log looks like this:

```
[2016-06-08 16:57:25] D [persister] Creating /srv/graphite/whisper/a/b/c.wsp {aggregation="default", method="average", retention="30s:8d,5m:90d", schema="foo-all", xFilesFactor=0.5}
```
