### ISSUE TITLE
Documentation point in wrong file

### ISSUE THREAD

**Issue by Knud3** [go-graphite/go-carbon#517]
In [deploy/storage-aggregation.conf](https://github.com/go-graphite/go-carbon/blob/master/deploy/storage-aggregation.conf#L10) and [deploy/storage-schemas.conf](https://github.com/go-graphite/go-carbon/blob/master/deploy/storage-schemas.conf#L12) is "`more in deploy/go-carbon.conf`"

That file is missing. Does it mean to point to [go-carbon.conf.example](https://github.com/go-graphite/go-carbon/blob/master/go-carbon.conf.example)?

**Comment by deniszh** [comment]
Hi @Knud3 ,

Thanks! Yes, indeed. Should be fixed.
