### ISSUE TITLE
How can I troubleshoot bad message further?

### ISSUE THREAD

**Issue by didip** [go-graphite/go-carbon#52]
Hi all,

First of all thank you for all the hard work on this project.

I am trying to use go-carbon to directly replace `carbon-cache.py`. When I run it, I received `bad message` error. Example:

```
[2016-06-15 21:46:08] I bad message: "aaa.bbb.value [J@4442a5df 1466027166\n"
```

I changed the log level to debug, and see no new information.

Looks like this is the line where it breaks: https://github.com/lomik/go-carbon/blob/ece1e95d74d158a8b82c261ad616ee02480c59e8/points/points.go#L60

That `[J@4442a5df` is suspicious, does that mean I am receiving pickle format, instead of plain text?

**Comment by lomik** [comment]
Hi, 

This is not pickle. Try to search problem in metric sender

**Comment by didip** [comment]
Wow, lightning response. You are correct. I have bad source data.

Sorry for wasting your time.
