### ISSUE TITLE
[Q] New release date

### ISSUE THREAD

**Issue by cboudereau** [go-graphite/go-carbon#535]
Is it possible to bump a new release since the v0.16.2 is a bit aged and the [master example conf](https://github.com/go-graphite/go-carbon/blob/master/go-carbon.conf.example) crashes with this error : 
`FATAL [main] failed to stat whisper data directory: lstat /var/lib/graphite/whisper: no such file or directory {}`

Linked to this one from 2020 : https://github.com/go-graphite/go-carbon/issues/333

Is it possible to have regular release like every X months ?

**Comment by deniszh** [comment]
Sure, let me create release tomorrow. We're using master in production, so, release schedule is irregular.
We can do releases by schedule, that's only matter of discipline :)

**Comment by cboudereau** [comment]
Thanks a lot!

**Comment by deniszh** [comment]
But please note that error above is valid and not a crash - go-carbon can't read configured whisper directory.

**Comment by cboudereau** [comment]
Ok but the question is why it is working with the same conf and the master version?

I also double check that the go function os.Lstat and the fact that the directory exists in the container for carbon user

**Comment by cboudereau** [comment]
I did not dig further but it seems that there is a conf mismatch. Note that I am quite a new go-carbon user though

**Comment by deniszh** [comment]
I released v0.17.1 (and v0.17.0 but forgot to bump version there), but not sure about issue which you mentioned. We're using master in production and it's working fine.

**Comment by cboudereau** [comment]
This issue was about using the v0.16.2 with the latest example.

Thank you for the release

**Comment by cboudereau** [comment]
Did you pushed a tag for docker images ?

**Comment by deniszh** [comment]
Yes, I did - https://github.com/go-graphite/go-carbon/pkgs/container/go-carbon

**Comment by cboudereau** [comment]
Thanks
