### ISSUE TITLE
Gaps in go carbon metrics

### ISSUE THREAD

**Issue by Ruksov-Andrey** [go-graphite/go-carbon#547]
Hello,

GOCARBON_VERSION=0.17.1
CARBONAPI_VERSION=0.16.0
metrics received per minute = 4.3 Mil

I see gaps for all metrics including carbon metrics
![image](https://user-images.githubusercontent.com/30682179/221845260-e8d4f242-9abb-4cae-9ddb-f1fbef51f8d8.png)

There are no errors in go carbon logs about this

**Comment by Ruksov-Andrey** [comment]
- increased cache max-size by 10 times
- downgrade to 0.15.3

**Comment by VtG242** [comment]
@Ruksov-Andrey Hi, are you still using  0.15.3. I saw something similar when I tried to switch from carbon-cache to go-carbon with 0.17.1 (2 Mill metrics)
