### ISSUE TITLE
Graphite-Web compatibility map?

### ISSUE THREAD

**Issue by toni-moreno** [go-graphite/go-carbon#55]
Hi @lomik I'm really surprised with this project , I would like to test it , but I need to know first if has been tested with both current graphite-web branches.
- master (0.10.X) ?
- 0.9.x  ?

I need also test with my currently working whisper files, can go-carbon work with  already created files with original whisper python tools?

**Comment by redbaron** [comment]
I am not the author, but AFAIK whisper format didn't change between graphite versions, therefore go-carbon should be fully compatible

**Comment by scr512** [comment]
I can confirm this works in my environment as I bake in graphite-web &
go-carbon in our internal docker image.

**Comment by lomik** [comment]
Compatible with all recent graphite-web versions.
Graphite older 0.9.10 (released 5/31/12) had another carbonlink protocol.
