### ISSUE TITLE
separate `bad mesage` from  `doCheckpoint()` log messages

### ISSUE THREAD

**Issue by redbaron** [go-graphite/go-carbon#57]
Right now bad message is reported with `info` level same as `doCheckpoint`, it would be really nice it they were separated,so that only `doCheckpoint()` messages were logged.

One option would be to introduce `notice` severity level betwern `info` and `warning` and make `doCheckpoint()` to log using `notice`. that way, by setting `log-level=notice` it would be possible to shut `bad message` messages.

Another option would be to move `bad message` to `debug` level

**Comment by AlexAkulov** [comment]
Now you can drop bad metrics on carbon-c-relay

**Comment by redbaron** [comment]
well, carbon-c-relay is a different project, you might as well said "you can stop producing bad metrics to solve it" :) . I see you commit now that it was moved to a debug level, I missed it earlier. It is what I wanted, so closing it. Thank you for  sorting it  out
