### ISSUE TITLE
[Q] Packages for Debian Bookworm

### ISSUE THREAD

**Issue by anayrat** [go-graphite/go-carbon#570]
Hello,
It seems packages are missing for Debian bookworm ? 
https://packagecloud.io/app/go-graphite/stable/search?q=&filter=all&dist=debian%2Fbookworm

Do you plan to publish them?
Thanks

**Comment by deniszh** [comment]
Thanks for fixing this! I can probably release 0.17.2, then you'll have bookworm package

**Comment by deniszh** [comment]
@anayrat : ah, but you neet to use 8 spaces in makefile first, because now it's failing:
```
Run make
Makefile:135: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
```
