### ISSUE TITLE
crash of 0.7.2 (and 0.7.1)

### ISSUE THREAD

**Issue by rtoma** [go-graphite/go-carbon#58]
Just had go-carbon-0.7.1-1.el6.x86_64 crashing.

I have included all info I could think. If you need more information or want me to run some additional diagnostics, please let me know.

Crash occurred at 22:01. The logs is totally silent:

```
[2016-06-23 21:58:24] I [carbonlink] Cache no reply (100ms timeout)
[2016-06-23 22:25:25] I started
```

I've been running go-carbon for some days ramping up the volume. This afternoon I put the peddle to the floor. Unsure if this is related, but its the biggest recent change.

Some numbers:
- tcp.metricsReceived = 5.1M (~ 80k/sec)
- cache.size = 21M
- cache.metrics = 3M (so ~7 datapoints/metric in cache)
- persister.updateOperations = 320k (~5300 update/sec == 90M/s write on flash)

My config:

```
[common]
user = ""
logfile = "/srv/graphite/log/go-carbon/go-carbon.log"
log-level = "info"
graph-prefix = "carbon.agents.{host}."
max-cpu = 4
metric-interval = "1m0s"

[whisper]
data-dir = "/srv/graphite/whisper/"
schemas-file = "/opt/graphite/conf/storage-schemas.conf"
aggregation-file = ""
workers = 4
max-updates-per-second = 7500
enabled = true

[cache]
max-size = 0
input-buffer = 5120000

[udp]
listen = ":2003"
enabled = false
log-incomplete = false

[tcp]
listen = "a.b.c.d:12003"
enabled = true

[pickle]
listen = ":2004"
enabled = false
max-message-size = 67108864

[carbonlink]
listen = "a.b.c.d:7002"
enabled = true
read-timeout = "30s"
query-timeout = "100ms"

[pprof]
listen = "localhost:7007"
enabled = false
```

Top output for the go-carbon pid:

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
14950 root      20   0 3671m 2.9g 4176 R 53.6  2.3  17:57.26 go-carbon
14948 root      20   0 3671m 2.9g 4176 S 40.3  2.3  18:29.81 go-carbon
14951 root      20   0 3671m 2.9g 4176 S 31.3  2.3  20:42.91 go-carbon
14947 root      20   0 3671m 2.9g 4176 R 29.0  2.3  20:48.62 go-carbon
14976 root      20   0 3671m 2.9g 4176 S 25.0  2.3  20:28.41 go-carbon
14953 root      20   0 3671m 2.9g 4176 S 24.0  2.3  20:45.73 go-carbon
14957 root      20   0 3671m 2.9g 4176 R 22.3  2.3  19:41.77 go-carbon
14941 root      20   0 3671m 2.9g 4176 R 13.3  2.3  19:32.04 go-carbon
14943 root      20   0 3671m 2.9g 4176 S  0.0  2.3   1:10.92 go-carbon
14944 root      20   0 3671m 2.9g 4176 S  0.0  2.3   0:00.00 go-carbon
14945 root      20   0 3671m 2.9g 4176 S  0.0  2.3   0:00.00 go-carbon
14946 root      20   0 3671m 2.9g 4176 S  0.0  2.3  20:39.26 go-carbon
14949 root      20   0 3671m 2.9g 4176 S  0.0  2.3  19:01.72 go-carbon
14954 root      20   0 3671m 2.9g 4176 S  0.0  2.3  19:50.05 go-carbon
14955 root      20   0 3671m 2.9g 4176 S  0.0  2.3  14:40.24 go-carbon
15466 root      20   0 3671m 2.9g 4176 S  0.0  2.3  14:47.81 go-carbon
```

**Comment by rtoma** [comment]
Just noticed, the official init script calls func daemon (from /etc/rc.d/init.d/functions) which throws away all output on el6:
```
        # And start it up.
        if [ -z "$user" ]; then
           $cgroup $nice /bin/bash -c "$corelimit >/dev/null 2>&1 ; $*"
        else
           $cgroup $nice runuser -s /bin/bash $user -c "$corelimit >/dev/null 2>&1 ; $*"
        fi
```

So maybe go-carbon threw a panic and it got lost. Will change our init script to catch the next (hope not) crash.

**Comment by rtoma** [comment]
After last crash I tuned go-carbon with:
- common.max-cpu=15
- whisper.workers=30
- catching of stdout/stderr in the init script (hoping a panic would be printed)

Go-carbon crashed again, without nothing in the stdout/err logging.

@lomik: can you suggest a way of finding the rootcause?

**Comment by rtoma** [comment]
upgrading to 0.7.2 assuming that go-whisper "return instead of panic" fix is related.

**Comment by rtoma** [comment]
crash on 0.7.2, still nothing in the stdout/err or logfile.

**Comment by lomik** [comment]
I have no idea. Empty log, stderr and stdout is very strange. 
May be carbon stopped by oom killer or something similar...
Have there been any deviations in the logs of carbon before the fall? (grep doCheckpoint)

**Comment by redbaron** [comment]
do you have anything in `dmesg` output? do you see core files created? what does `sysctl kernel.core_pattern` show?

**Comment by rtoma** [comment]
Sorry for the delayed response. These crashes and total silence, even when running go-carbon in foreground, was reason to go back to a carbon-cache setup. I would have preferred to work with you to fix this issue, but after 4 crashes and no clues I had no choice. I had to rollback and threw more hardware at it.
