### ISSUE TITLE
[Q] Is "workers" effectively bound to "max-cpu"?

### ISSUE THREAD

**Issue by interfan7** [go-graphite/go-carbon#581]
If `max-cpu` is the maximum number of threads which can be executed simultaneously (right?), then it doesn't make sense to set `workers` to anything higher than that, because the won't process at the same time?

Or, there is still a benefit of having multiple workers waiting on disk I/O as the latter may be potentially batched?

**Comment by deniszh** [comment]
Indeed, workers is more related to disk writes, not cpu.

вс, 17 мар. 2024 г., 21:50 Leonid Brandes ***@***.***>:

**Comment by deniszh** [comment]
PS: and max-cpu just setting GOMAXPROC internally, limiting go concurrency, hence used cpu cores.
But exact workers value depends on hardware, so require some guessing/tuning

**Comment by interfan7** [comment]
Would you say there is some relation between `max-cpu` and `workers`?

In the example config file, the `max-cpu` has this comment above it:

```
# Increase for configuration with multi persister workers
```

**Comment by deniszh** [comment]
I would say workers should be <= max-cpu/2, but definitely < max-cpu.
