### ISSUE TITLE
[Q] INFO [pickle] can't parse message:

### ISSUE THREAD

**Issue by itinneed2022** [go-graphite/go-carbon#615]
Python Version 3.6.8
Graphite 1.10.0

I'm seeing this error message when trying to send metrics via python to go-carbon:
`[2024-08-01T06:27:37.367-0400] INFO [pickle] can't parse message {"data": "\ufffd\u0002]q\u0000(XC\u0000\u0000\u0000infra.vmware.vm.homebrew01_node.cpu_ready_percentq\u0001X\u000c\u0000\u0000\u00001722502800.0q\u0002X\u0004\u0000\u0000\u00000.46q\u0003\ufffdq\u0004\ufffdq\u0005XC\u0000\u0000\u0000infra.vmware.vm.homebrew01_node.cpu_usage_averageq\u0006h\u0002X\u0005\u0000\u0000\u000019.07q\`

I found this issue where a user had a similar problem: https://github.com/go-graphite/go-carbon/issues/430

So looking at my code:
```
def send(self):
        payload = pickle.dumps(self.batch, protocol=2)
        header = struct.pack("!L", len(payload))
        message = header + payload

        if self.debug:
            print(self.batch)


        # open socket
        hostaddr = socket.gethostbyname(self.server)
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.connect((hostaddr, self.port))
        
        try :
            #Send the whole message
            sock.sendall(message)
        except socket.error:
            #Send failed
            print("carbon metrics data send failed")
            sys.exit()
        print("carbon metrics data send complete")
        sock.close
        self.flush()
```

So the protocol is being specified, but go-carbon is rejecting the metrics. Any ideas?

**Comment by deniszh** [comment]
Unfortunately, we didn't use pickle support, and I'm not sure if it works at all. protocol=2 should be safe bet but I never tested it tbh. 
Also, from speed perspective normal line protocol is faster that pickle, so, if you're implementing sending metrics it's better to use port 2003 and line protocol.

**Comment by itinneed2022** [comment]
Was pickle supported in python carbon?

**Comment by deniszh** [comment]
It was. Well, it's implemented in go-carbon too, I just didn't check it for modern python version

**Comment by itinneed2022** [comment]
I'm sorry I don't follow. Pickle is supported in go-carbon or it is not?

**Comment by itinneed2022** [comment]
Re-reading the docs, this project does support pickle protocol: https://github.com/go-graphite/go-carbon

**Comment by itinneed2022** [comment]
Found the issue. We were passing our time values at floats converted to strings, example: " 1724080272.0". This threw the error above. changing the python code to strong-type our time values as int, converting that to a string, and its working again.
