### ISSUE TITLE
Datapoints (for new metric) not flushed to disk, but kept in cache memory

### ISSUE THREAD

**Issue by rtoma** [go-graphite/go-carbon#63]
Curious case.

Our setup:
- 2 nodes
- node1 runs go-carbon
- node2 runs 12 carbon-cache daemons
- carbon-c-relay on both nodes sending each line received to go-carbon on node1 and one of the carbons on node2

Expected: so each node should have the same whisperfiles

In reality: for 99.99% of all metrics its true, but we've found an edge case.

What happens:
- User sends a new metric with sporadic datapoints
- Points have been flushed to disk by carbon-cache and whisper fils have been created
- Go-carbon hasn't flushed them yet, so no whisper files exist

It seems go-carbon is holding on to the datapoints in cache memory.
Carbonlink query on go-carbon returns this:

```
[(1467718603, 0.0),
(1467720962, 5.0),
(1467722489, 5.0),
(1467724363, 5.0),
(1467726788, 5.0),
(1467727826, 5.0),
(1467790086, 2106.0)]
```

That 1st timestamp is 22 hours ago.

Using this script to query:

```
#!/usr/bin/env python
import sys
sys.path.append('/opt/graphite/webapp')

import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "graphite.settings")
from graphite import settings
settings.LOG_DIR = '.'
del settings.ADMIN_MEDIA_PREFIX
del settings.CACHE_BACKEND

from graphite.render import datalib as dl

def query(metric):
  hosts = []
  for e in settings.CARBONLINK_HOSTS:
    host, port, instance = e.split(':')
    hosts.append((host, int(port), instance))

  p = dl.CarbonLinkPool(hosts, 1.0)
  print p.query(metric)

for m in sys.argv[1:]:
  query(m)
```

**Comment by AlexAkulov** [comment]
Use this settings

```
[cache]
...
write-strategy = "sorted"
```

**Comment by rtoma** [comment]
Thanks @AlexAkulov for replying. Having taken a look at the source your suggestion will ensure my 'sleepy' metric will get flushed:

```
    if c.writeStrategy == "max" {
        sort.Sort(byLength(newQueue))
    } else {
        sort.Sort(byTimestamp(newQueue))
    }
```
