### ISSUE TITLE
Define a different endpoint for internal metrics

### ISSUE THREAD

**Issue by nisc-acooper** [go-graphite/go-carbon#68]
Perhaps I am the only one interested in this.  I would like to be able to send the internal go-carbon metrics (carbon.agents.*) to a defined endpoint instead of only to the local persister.  The use case would be sending to a load balancer/relay endpoint so that internal metrics get stored on multiple cache nodes.

**Comment by lomik** [comment]
Solved in master (see changelog)

**Comment by nisc-acooper** [comment]
I have tested with latest master and can confirm stats are working through the tcp endpoint.  Thanks for getting this into the code base!
