### ISSUE TITLE
CommittedPoints equivalent to native graphite CommittedPoints?

### ISSUE THREAD

**Issue by genericgithubuser** [go-graphite/go-carbon#69]
Can someone clarify/confirm if the go-carbon CommittedPoints internal persister counter is equivalent to the py-carbon counter of the same name?  
I'm trying to get go-carbon in place to replace py-carbon on our internal (6m points min) setup.  On identical hardware, for py-carbon I get 375k committedpoints a minute per server (running 4 instances).  On go-carbon the committed points averages <200k per minute. 

Server is using EBS SSD, 16GB RAM, 4 proc

 I've tried the following combinations of settings:

max-updates-per-second = [tried 0, 500, 1000, 10000]
max-cpu = [3, 4] note: 4 cpu server
workers = [6, 8, 18]
max-size = [1000000, 5000000]
write-strategy = [max, sorted]
input-buffer = [51200, 512000, 5120000]
max-message-size = 67108864

The server is only getting metrics from a carbon-relay-ng server, and all stats are over pickle since this is running next to the py-carbon servers.  Right now metrics are being dumped in at almost 800k metrics a minute (caches full, overflow shows ~600k metrics a min dropped). Are there other settings I should be aware of that would cause a significant performance differences, or are the metrics representing different things so I'm not actually comparing apples to apples?  

go-carbon built yesterday so recent code release.

**Comment by deniszh** [comment]
Yes, but check PPU (points per update) also. go-carbon should has lower commitedpoints but higher ppu.

**Comment by genericgithubuser** [comment]
Thanks for the feedback Denishzh!  
Unfortunately, py whisper was sitting at about the same (very slightly higher actually).  I've been trying every combination that seems reasonable of settings (starting with some base settings put out by lomik
 in a separate thread), and have even started down the path of modifying OS parameters to try to get go-carbon to be at least equally as fast (since that would still make it worth using since I like the simple config vs having 4 py processes runnign.  Unfortunately latest go with latest go-carbon, and even trying the version of go-carbon in the last packaged release just isn't matching up.  
If anyone has come across some settings not in the configs that made a significant performance difference, please let me know.  Unfortunately I'm not go-saavy enough yet to be able to see what's actually causing the gap between performance on these systems.  I swapped configs between the server running the py version and the go version just to make sure it wasn't something funny with the server or (4 striped ebs ssd volumes) supporting it.   The numbers were the same on the switched hardware too, so no luck there.

**Comment by deniszh** [comment]
Sorry, not understand what you mean. Is `PPU * CommitedPoints` for Py carbon equal to `PPU * CommitedPoints` for go-carbon? That's good; that means that go-carbon works fine - both doing its job. You need to test it on some test load to find out max performance.
E.g check this slides - http://www.slideshare.net/VsevolodPolyakov/metrics-where-and-how - author there reports that go-carbon almost two times faster than Python one (300K vs. 180K).

**Comment by deniszh** [comment]
I didn't find any difference between go-carbon with eight writers and eight python-carbon daemons. Didn't run artificial tests, though.

**Comment by genericgithubuser** [comment]
Sorry my previous comment wasn't clear.  I was saying that the PPU was about the same (though slightly higher for py).  So if I take PPU \* committedPoints, the total is significantly higher for py (close to 200k per minute).  That being said, I thought committedPoints was the total points, and was already more of a reflection of PPU \* updateOperations.  
I have been load testing these, and was hoping to get some insight into what others were seeing.  Unfortunately from those slides, it is not fully clear how many whisper instances he was trying to run per server.  There is an image that shows that he tries multiple py-instances, but not much on proc usage across all cores.  From what I'm seeing, go-carbon greatly outperforms a single py-carbon process.  My challenge right now is that for the server type I'm running, if I run 4 py-carbon processes, I get much better performance than I see with go-carbon (as previously stated).  This is on identical hw (even tested on the same exact hw), using the same stresser metrics coming in at the same rate.  I do like the simplicity of go-carbon, and was very excited to have it be simpler and faster.  Unfortunately with days of testing different settings, it's just not getting close to being faster than the number of metrics I can commit with multiple (4) py-whisper processes on a single server, so my per-server ingestion rate goes down.

**Comment by genericgithubuser** [comment]
Uff, didn't mean to click the close button.  I'd be very interested in hearing if there are others that directly compared the multiple py processes vs go, or if there are some settings I should be considering.  A lot of tweaking had been done to the py carbon processes (not code, just tweaking configs, re-testing, etc.) so I'd like to make sure I'm not missing something with go-carbon before ruling it out as the way forward for us (for now).

**Comment by ctrlok** [comment]
@genericgithubuser I get a performance like 200,000 metric\s per m4.xlarge instance with enabling sparse file and limiting max_update to actual io what I have.

**Comment by deniszh** [comment]
> go-carbon should has lower commitedpoints but higher ppu.

PS: sorry for misleading, my point was wrong.
https://github.com/lomik/go-carbon/blob/b45eebf2da9f28790bafa13cfbc90e67ded88c6e/persister/whisper.go#L221-L225 - that means that `commitedPoints = PPU * updateOperations`, so, you should easily compare commitedPoints for go-carbon and python carbon.
Not sure why you still getting lower numbers with go-carbon, it's really counter-intuitive.
