### ISSUE TITLE
Agent metrics questions

### ISSUE THREAD

**Issue by druchoo** [go-graphite/go-carbon#7]
Many metrics are reporting 0. Some are expected but some not. For example cache.queries, I wouldn't expect that to be 0. What is cache.checkpointTime and cache.metrics? Why are some of the *.active metrics 0 when they are enabled in the config?

![screen shot 2015-04-22 at 6 56 38 pm](https://cloud.githubusercontent.com/assets/2237523/7287327/7ebc3f4e-e921-11e4-9345-f4ec7fbb710a.png)

**Comment by lomik** [comment]
I will try to add a description of metrics in the documentation soon.

In brief:
- cache.queries - requests from graphite-web via "carbonlink" per minute. May be disabled in your graphite-web
- cache.checkpointTime - every minute cache reorder "save_to_persister" queue. Your cache size small -  checkpoint very fast. This is float value - could be rounded to zero in your dashboard.
- cache.metrics - metrics in cache (graphs)
- cache.size - points in cache (one metric can have more than one point in cache)
- *.active - Count of currently established tcp connections to pickle or tcp receiver. Your -1 value may be bug :(

**Comment by druchoo** [comment]
Ok makes sense now. Thanks for clarification.
