### ISSUE TITLE
Add runtime tunables to internal metrics

### ISSUE THREAD

**Issue by drawks** [go-graphite/go-carbon#70]
It would be nice if various of the runtime tunables were exported as internal metrics. For instance cache max-size and input-buffer would more easily allow for you to create dashboard which show that you are approaching an internal limit before you start dropping metrics. Or whisper workers or max -cpu would allow you to better understand how work is divided and how it scales when tuning. These become especially informative if your carbon/graphite stack is evolving over time as it allows for easier growth trend analysis.

**Comment by lomik** [comment]
Released in 0.9.0
