### ISSUE TITLE
Revert to github.com/sevlyar/go-daemon

### ISSUE THREAD

**Issue by drawks** [go-graphite/go-carbon#73]
It looks like this was originally forked and the fork set as a dependency while there was an open PR. However that PR has since been merged in sevlyar/go-daemon#6

**Comment by drawks** [comment]
Glad this got merged, but it seems you deleted the old repo which breaks all tagged versions since the referenced submodules doesn't exist. Please tag a new version AND/OR bring back your fork of go-daemon so tagged versions still build.

**Comment by lomik** [comment]
Oops. Recovered https://github.com/lomik/go-daemon
