### ISSUE TITLE
Cut a new version?

### ISSUE THREAD

**Issue by drawks** [go-graphite/go-carbon#76]
It looks like we are about 15 commits ahead of the last version and includes:
- new feature
  - sorted write strategy
- distro packaging changes
  - reload in redhat init
  - debian init script arg passing fixed
- vendored library changes
  - revert to github.com/sevylar/go-daemon
  - include github.com/kardianos/osext

Seems, to me, like we should tag 0.8.0

Is there any roadmap or outstanding issues to resolve before then?

**Comment by lomik** [comment]
I think to make 0.7.3. I plan to include a more significant changes in version 0.8

**Comment by drawks** [comment]
in the strict semantic version sense of things you should bump the minor version when you add features in a backwards compatible way. So I think sorted write strategy wants 0.8.0, the other changes I mentioned could go in 0.7.3.

**Comment by lomik** [comment]
Semantic versioning is not about graphite project ;)
0.7.3 released

**Comment by drawks** [comment]
Thats too bad, semver is pretty nice for being able to evaluate expectations between versions.
