### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by druchoo** [go-graphite/go-carbon#8]
Hey there, love this project so far. Just wondering if you have a roadmap. I'd like to see the following features from carbon-cache implemented. Currently, the writes to my storage is higher than I'd like.
- MAX_UPDATES_PER_SECOND
- MAX_CREATES_PER_MINUTE
- CARBON_METRIC_INTERVAL

**Comment by lomik** [comment]
I do not have a roadmap. All planned features I did and accept feature requests.

I'll see how to implement MAX_UPDATES_PER_SECOND, MAX_CREATES_PER_MINUTE, CARBON_METRIC_INTERVAL in carbon-cache and may also implement them. The original purpose was the opposite - to write as soon as possible :)

**Comment by lomik** [comment]
whisper.max-updates-per-second supported in version 0.4.3. Try it and report about results please

MAX_CREATES_PER_MINUTE not compatible with go-carbon internal architecture

**Comment by druchoo** [comment]
Thanks for implementing. It seems to work as expected. Any progress on CARBON_METRIC_INTERVAL? Setting interval to 10s in carbon-cache really helps with debugging and testing settings quickly.

**Comment by xneo64** [comment]
Hi @lomik any plans on implementing a similar config setting to CARBON_METRIC_INTERVAL?

**Comment by lomik** [comment]
`metric-interval` option added to master

**Comment by xneo64** [comment]
@lomik nice, thanks!

**Comment by lomik** [comment]
Released in 0.6
