### ISSUE TITLE
Tests indicate races in cache and receiver

### ISSUE THREAD

**Issue by drawks** [go-graphite/go-carbon#83]
I'm not super familiar with the race detector in go, so I'm uncertain if this is indicative of a race in the test code vs a race in the library code being tested. Either way, I suspect it should be cleaned up and the race detector enabled in the "test" make target so it gets better coverage in travis.

```
$ go test -race ./cache
....

==================
PASS
Found 9 data race(s)
FAIL    github.com/lomik/go-carbon/cache    1.570s
```

```
$ go test -race ./receiver

....

==================
PASS
Found 19 data race(s)
FAIL    github.com/lomik/go-carbon/receiver 1.170s
```

**Comment by drawks** [comment]
After poking at this for a little bit I think the race is actually in `logging.Test` which allows an unsynchronized bytes.Buffer to be written/read in different goroutines. I'm actually a little puzzled by how the logging package is envisioned to be used since I see the `logrus` package directly imported and used all over the place and even a smattering of the standard library `log` gets used during the initialization of carbon-agent.

FWIW I /think/ we should be initializing a logrus logger instance in the `lomik/go-carbon/logging` package and then providing that logger to all the various packages that want to log things.

It looks like `logrus` also provides some decorated logger instances designed as testing shims. I'm going to take a quick crack at converting the racy tests to use these facilities directly for now and perhaps try and do a logging overhaul in another issue/pr.

**Comment by lomik** [comment]
Some races fixed here https://github.com/lomik/go-carbon/commit/87068714a87493500227cb50679186ca17942046

Nothing interesting, only tests code affected

```
$ go test -race ./cache
...
==================
PASS
Found 1 data race(s)
FAIL    go-carbon/cache 1.608s


$ go test -race ./receiver
ok    go-carbon/receiver 1.242s
```

There was only one problem

```
go test -race ./cache
==================
WARNING: DATA RACE
Read by goroutine 44:
  github.com/Sirupsen/logrus.(*Entry).Debugf()
...

Previous write by goroutine 39:
  github.com/Sirupsen/logrus.SetLevel()
...

==================
PASS
Found 1 data race(s)
FAIL    go-carbon/cache 1.602s
```

Race condition in logrus:  https://github.com/Sirupsen/logrus/issues/295
Also only in tests (really not affected, but auto detected). In normal operation, the logging level is made once at the start (before first log attempt from concurrent thread) and never changing.
There is a chance that the fix in the near future https://github.com/Sirupsen/logrus/pull/374

**Comment by drawks** [comment]
Great! I'm eager for this to be fixed so we can add race detection to standard Travis tests.
