### ISSUE TITLE
Spurious test failure seen in Travis

### ISSUE THREAD

**Issue by drawks** [go-graphite/go-carbon#87]
```
?       _/home/travis/gopath/src/github.com/drawks/go-carbon    [no test files]
--- FAIL: TestCarbonlink-2 (0.05 seconds)
    Location:   carbonlink_test.go:115
    Error:      Not equal: "\x80\x02}(X\n\x00\x00\x00datapoints](J\xd3)\xceTG\xc0E\x11\xeb\x85\x1e\xb8R\x86J\xbe$\xceTG@.\x00\x00\x00\x00\x00\x00\x86eu." (expected)
                    != "\x80\x02}(X\n\x00\x00\x00datapoints](J\xd3)\xceTG\xc0E\x11\xeb\x85\x1e\xb8R\x86eu." (actual)

    Location:   carbonlink_test.go:139
    Error:      Not equal: "\x80\x02}(X\n\x00\x00\x00datapoints](eu." (expected)
                    != "\x80\x02}(X\n\x00\x00\x00datapoints](J\xbe$\xceTG@.\x00\x00\x00\x00\x00\x00\x86eu." (actual)

FAIL
FAIL    _/home/travis/gopath/src/github.com/drawks/go-carbon/cache  0.562s
```

While checking in something completely unrelated, I noticed this test error pop on travis for a go1.3 based build. Not sure if it may be related to #83 or not

**Comment by lomik** [comment]
>  Not sure if it may be related to #83 or not

Most likely you're right. Perhaps this race was to blame https://github.com/lomik/go-carbon/commit/87068714a87493500227cb50679186ca17942046#diff-e648ab02e8f8bc645ee3db96ece8ca4bR39

But perhaps the reason is something else. Hard to say for sure, because I can't reproduce it

**Comment by drawks** [comment]
I can reliably reproduce this error by running the cache tests in a loop:

`err=0; while [ ${err} = 0 ]; do go test -v -race ./cache ; err=$?; done`

`--- FAIL: TestCarbonlink (0.00s)
        Error Trace:    carbonlink_test.go:102
    Error:      Not equal: "\x80\x02}(X\n\x00\x00\x00datapoints](J\xd3)\xceTG\xc0E\x11\xeb\x85\x1e\xb8R\x86J\xbe$\xceTG@.\x00\x00\x00\x00\x00\x00\x86eu." (expected)
                    != "\x80\x02}(X\n\x00\x00\x00datapoints](J\xd3)\xceTG\xc0E\x11\xeb\x85\x1e\xb8R\x86eu." (actual)

```
    Error Trace:    carbonlink_test.go:127
Error:      Not equal: "\x80\x02}(X\n\x00\x00\x00datapoints](eu." (expected)
                != "\x80\x02}(X\n\x00\x00\x00datapoints](J\xbe$\xceTG@.\x00\x00\x00\x00\x00\x00\x86eu." (actual)
```

`

I suspect the cause is that the cache for the test run relies on some go routines causing the population of the cache from a channel to be asynchronous to the test function which is expecting the 3 values to be present in the cache to generate the expected carbonlink query results.

**Comment by redbaron** [comment]
```
for {
                c := <-cache.Out()
                cache.Confirm() <- c
                if c.Metric == "carbon.agents.carbon_agent_server.param.size" {
                        break
                }
        }

        _, err = conn.Write([]byte(sampleCacheQuery2))
```

Confirm() message is not guaranteed to be processed before query message which is initiated from same goroutine in quick succession.

Adding small sleep should help, but ideally a spin loop checking for desired counts in cache stats should be used instead
