### ISSUE TITLE
Carbonlink should support all relevant query types supported in mainline carbon

### ISSUE THREAD

**Issue by drawks** [go-graphite/go-carbon#97]
It looks like mainline carbon supports 4 types of queries in the carbonlink protocol (https://github.com/graphite-project/carbon/blob/77e1eb09b9708c91ffbca6e94ffd46e1143b04ee/lib/carbon/protocols.py#L127-L176) 
- `cache-query` - returns datapoints coalesced from whisper as well as in memory. This is supported in go-carbon and AFAICT is implemented completely.
- `cache-query-bulk` - same as `cache-query` but allows requesting an array of metrics instead of a single metric.
- `get-metadata` \ `set-metadata` - These probably don't need to be added. AFAICT these methods are original to the carbonlink protocol (https://github.com/graphite-project/carbon/commit/7549c5c3cd5917a1deb7fed8b58a28b528b2eb49) but have been unused in any discernable way.

**Comment by drawks** [comment]
Additionally, I think `cache.CarbonlinkRequest` type doesn't match the required signature for unpacking all valid carbonlink requests. I /think/ it should be something like:

```
type CarbonlinkRequest struct {
        Type        string // Required
        Metric      string // Required for cache-query
        Metrics    []string // Required for cache-query-bulk
        Key         string // Required for get-metadata and set-metadata
        Value      string // Required for set-metadata
}
```

**Comment by redbaron** [comment]
I am not sure where they are used. 

webapp/graphite/carbonlink.py does only `cache-query` requests

**Comment by deniszh** [comment]
> webapp/graphite/carbonlink.py does only cache-query requests

Master branch - yes, 0.9.x has `cache-query-bulk` implemented. But maybe it's not so relevant, because nobody yet ported that to a master, and next release will be done from the master...

**Comment by lomik** [comment]
cache-query-bulk is not supported by graphite-web 1.0+ :(
